### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jjyuhub** [ggerganov/llama.cpp#102]
Bug encountered when running `python3 convert-pth-to-ggml.py models/7B/ 1`:

```
llama.cpp % python3 convert-pth-to-ggml.py models/7B/ 1
Traceback (most recent call last):
  File "/Users/jjyuhub/llama.cpp/convert-pth-to-ggml.py", line 69, in <module>
    hparams = json.load(f)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by prusnak** [comment]
I am pretty sure your download is broken.

**Comment by gjmulder** [comment]
See my comments in issue #53 for md5 signatures of *.pth and *.bin files to verify your torrent downloads are legitimate and correct.
