### ISSUE TITLE
OSError: [Errno 22] Invalid argument when running convert.py

### ISSUE THREAD

**Issue by PaulShiLi** [ggerganov/llama.cpp#1045]
Having this issue of an invalid argument for ZipFile_object.open: 
```bash
sub01@Sub01-Lenovo:~/Documents/code/hackathon/src/llama.cpp$ python3 convert.py models/13B/
Loading model file models/13B/consolidated.00.pth
Loading model file models/13B/consolidated.01.pth
Traceback (most recent call last):
  File "/home/sub01/Documents/code/hackathon/src/llama.cpp/convert.py", line 1149, in <module>
    main()
  File "/home/sub01/Documents/code/hackathon/src/llama.cpp/convert.py", line 1129, in main
    model_plus = load_some_model(args.model)
  File "/home/sub01/Documents/code/hackathon/src/llama.cpp/convert.py", line 1055, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/home/sub01/Documents/code/hackathon/src/llama.cpp/convert.py", line 849, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/home/sub01/Documents/code/hackathon/src/llama.cpp/convert.py", line 717, in lazy_load_torch_file
    pickle_fp = zf.open(pickle_paths[0], 'r')
  File "/usr/lib/python3.10/zipfile.py", line 1532, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib/python3.10/zipfile.py", line 746, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
```

My current folder structure for models looks like:
```
├── 13B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   └── params.json
├── ggml-vocab.bin
├── tokenizer.model
└── tokenizer_checklist.chk
```

My current OS is WSL Ubuntu 20.04.5 running python 3.10.11 and this code is directly pulled from master!

Any solutions to this? Thanks!

**Comment by prusnak** [comment]
Check the hashes of the download files:

```
sha256sum --ignore-missing -c SHA256SUMS
```

and post the result here

**Comment by PaulShiLi** [comment]
Ah I see! The pth files are probably corrupted since the sha256 are different so I will be redownloading them!

For my sha256sum:
models/13B/consolidated.00.pth ab545af6c3e8dfe53f66825b8aab268818b69a6ccbdb4e7e8e4c3fe5cf20a039
models/13B/consolidated.01.pth c09ea2cbe3d511dbd759da295dee80d66f1cd59194775ce0fc3d41464ae089f4
els/13B/params.json 4ab77bec4d4405ccb66a97b282574c89a94417e3c32e5f68f37e2876fc21322f
