### ISSUE TITLE
[Bastian1110] tTrouble using convert.py with meta provided models

### ISSUE THREAD

**Issue by Bastian1110** [ggerganov/llama.cpp#1643]
# Expected Behavior

Im trying to convert the 7B model provided by meta-research to ggml FP16 format, using the command provided in the llama.cpp/README.md, here is my current `./models` directory: 

```
# ls ./models
7B                      tokenizer.model
ggml-vocab.bin          tokenizer_checklist.chk

# ls ./models/7B
checklist.chk       consolidated.00.pth params.json
```
When I run `python3 convert.py models/7B/ `, I would expect it to generate the `./models/7B/ggml-model-f16.bin` file.

# Current Behavior

The problem, is that when I run `python3 convert.py models/7B/ ` I get the following error : 
```
Loading model file models/7B/consolidated.00.pth
Loading vocab file models/tokenizer.model
Traceback (most recent call last):
  File "/Users/sebmora/Documents/Codes/Python/AI/llama.cpp/convert.py", line 1168, in <module>
    main()
  File "/Users/sebmora/Documents/Codes/Python/AI/llama.cpp/convert.py", line 1156, in main
    vocab = load_vocab(vocab_dir)
  File "/Users/sebmora/Documents/Codes/Python/AI/llama.cpp/convert.py", line 1100, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None)
  File "/Users/sebmora/Documents/Codes/Python/AI/llama.cpp/convert.py", line 158, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
  File "/Users/sebmora/Library/Python/3.9/lib/python/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/Users/sebmora/Library/Python/3.9/lib/python/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/Users/sebmora/Library/Python/3.9/lib/python/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: unk is not defined.
```

I don't know if the way I pouted the files inside the `./models` directory is correct, it seems that the error is that it's not finding the vocab (which I think is the `tokenizer.model` file). Also, when I try to run it using the `convert-pth-to-ggml.py`(which I think its deprecated) script, I get the same error. 

# Environment and Context

I downloaded the models from the form provided by meta-research, but I'm only trying to work with the 7B model, I moved the 7B directory to `llama.cpp/models` I also copied the `tokenizer.model` and `tokenizer_checklist.chk` to the `llama.cpp/models` directory.  

# Hardware and OS
I'm running al this in a MacBook Air with the M2 chip, 16GB of RAM, on Ventura 13.2.1 and Python3 version 3.9.6

**Comment by hstringa01** [comment]
I am experiencing the same on a M1.
