### ISSUE TITLE
After Converting my LLaMa file to HF, zip file error trying to convert to GGML. 

### ISSUE THREAD

**Issue by langem** [ggerganov/llama.cpp#1844]
(pytorch) michael@panettone llama.cpp % python3 convert.py ~/out --outtype f32
Loading model file /Users/michael/out/pytorch_model-00001-of-00003.bin
Loading model file /Users/michael/out/pytorch_model-00001-of-00003.bin
Loading model file /Users/michael/out/pytorch_model-00002-of-00003.bin
Loading model file /Users/michael/out/pytorch_model-00003-of-00003.bin
Traceback (most recent call last):
  File "/Users/michael/llama.cpp/convert.py", line 1168, in <module>
    main()
  File "/Users/michael/llama.cpp/convert.py", line 1148, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/llama.cpp/convert.py", line 1074, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/llama.cpp/convert.py", line 864, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/llama.cpp/convert.py", line 729, in lazy_load_torch_file
    zf = zipfile.ZipFile(outer_fp)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/anaconda3/envs/pytorch/lib/python3.11/zipfile.py", line 1301, in __init__
    self._RealGetContents()
  File "/Users/michael/anaconda3/envs/pytorch/lib/python3.11/zipfile.py", line 1368, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by BagpipesRbetter** [comment]
I'm having a similar problem with the "zipfile.py" saying bad zip file 

***(llama2) evanbarclay@MacBook-Pro-2 llama.cpp % sudo python3 convert.py --outfile /models/ggml-model-f16.bin --outtype f16 ../llama/llama-2-70b
Password:
Loading model file ../llama/llama-2-70b/consolidated.00.pth
Loading model file ../llama/llama-2-70b/consolidated.01.pth
Loading model file ../llama/llama-2-70b/consolidated.02.pth
Traceback (most recent call last):
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1264, in <module>
    main()
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1244, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1165, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 955, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 819, in lazy_load_torch_file
    zf = zipfile.ZipFile(outer_fp)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/miniconda3/envs/llama2/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/Users/evanbarclay/miniconda3/envs/llama2/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
(llama2) evanbarclay@MacBook-Pro-2 llama.cpp % sudo python3 convert.py --outfile /models/ggml-model-f16.bin --outtype f16 ../llama/llama-2-70b
Password:
Loading model file ../llama/llama-2-70b/consolidated.00.pth
Loading model file ../llama/llama-2-70b/consolidated.01.pth
Loading model file ../llama/llama-2-70b/consolidated.02.pth
Traceback (most recent call last):
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1264, in <module>
    main()
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1244, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 1165, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 955, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/Desktop/llama2/llama.cpp/convert.py", line 819, in lazy_load_torch_file
    zf = zipfile.ZipFile(outer_fp)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanbarclay/miniconda3/envs/llama2/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/Users/evanbarclay/miniconda3/envs/llama2/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file***

**Comment by phamkhactu** [comment]
Hi @langem @BagpipesRbetter 
 
I have encountered the same problems.
Have you found any information?

**Comment by BagpipesRbetter** [comment]
yeah I did the larger the model the more ram you need so for the 7b model you need at least 7gb of ram and so forth so the reason I count run or convert the 70b model is because I don't have 70gb of free ram so I just tried the smaller 7b model and it worked perfectly for me, hope this helps and sorry if its unreadable I'm speed typing on my phone
