### ISSUE TITLE
[bug] Cannot quantize

### ISSUE THREAD

**Issue by Freed-Wu** [ggerganov/llama.cpp#2211]
## Reproduce Procedures

```shell
$ git clone --depth=1 https://huggingface.co/openlm-research/open_llama_13b
$ git clone --depth=1 https://github.com/ggerganov/llama.cpp
$ cd llama.cpp
$ nix build
$ result/bin/convert.py ../open_llama_13b --outtype q4_0
Loading model file ../open_llama_13b/pytorch_model-00001-of-00003.bin
Loading model file ../open_llama_13b/pytorch_model-00001-of-00003.bin
Loading model file ../open_llama_13b/pytorch_model-00002-of-00003.bin
Loading model file ../open_llama_13b/pytorch_model-00003-of-00003.bin
Loading vocab file ../open_llama_13b/tokenizer.model
params: n_vocab:32000 n_embd:5120 n_mult:256 n_head:40 n_layer:40
Traceback (most recent call last):
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 1264, in <module>
    main()
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 1257, in main
    model = convert_to_output_type(model, output_type)
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 1097, in convert_to_output_type
    return {name: tensor.astype(output_type.type_for_tensor(name, tensor))
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 1097, in <dictcomp>
    return {name: tensor.astype(output_type.type_for_tensor(name, tensor))
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 569, in astype
    self.validate_conversion_to(data_type)
  File "/home/wzy/Desktop/llama.cpp/result/bin/convert.py", line 580, in validate_conversion_to
    raise Exception(f"Can't turn an unquantized tensor into a quantized type ({data_type})")
Exception: Can't turn an unquantized tensor into a quantized type (QuantizedDataType(groupsize=32, have_addends=False, have_g_idx=False))
```

Different from #1347, `result/bin/convert.py ../open_llama_13b` can work for me.

**Comment by pnb** [comment]
I don't think the convert.py script is intended for quantization -- that's what `quantize` is for. Try remove the `--outtype` parameter from convert.py to run conversion, then quantize with something like:

```bash
./quantize ../open_llama_13b/ggml-model-f16.bin ../open_llama_13b/openllama-ggml-q5km.bin Q5_K_M
```

**Comment by Freed-Wu** [comment]
So `--outtype` is an invalid option?

**Comment by pnb** [comment]
It is a valid option, it just isn't for quantization. Normally the numerical precision of the model should be automatically detected (https://github.com/ggerganov/llama.cpp/blob/master/convert.py#L1067), but sometimes it is necessary to override it in special cases (https://github.com/ggerganov/llama.cpp/blob/master/convert.py#L584). I expect this is why `--outtype` has only a few choices, for situations where overriding might be necessary during conversion (not quantization), whereas `./quantize -h` will show that the quantization step has many possible choices.

**Comment by Freed-Wu** [comment]
OK, I see. I think the name of `--outtype` is misleading and let people misunderstand it can control the output quantization. :cry:
