### ISSUE TITLE
Convert.py issue

### ISSUE THREAD

**Issue by okanduzyel** [ggerganov/llama.cpp#2516]
Hi, 

I have got that error listed below. Files are okay and placed in this folders but I am getting that error.

```
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 ~/llama2/meta_models/llama-2-7b-chat
Loading model file /Users/okanduzyel/llama2/meta_models/llama-2-7b-chat
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1319, in <module>
    main()
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1299, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1214, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1000, in lazy_load_file
    fp = open(path, 'rb')
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/okanduzyel/llama2/meta_models/llama-2-7b-chat'
```

**Comment by MrDevel0per** [comment]
Would you please run `ls /Users/okanduzyel/llama2/meta_models` and share the result here? This will show all of the contents of that folder.

**Comment by okanduzyel** [comment]
<img width="1151" alt="Screenshot 2023-08-05 at 13 57 09" src="https://github.com/ggerganov/llama.cpp/assets/38145537/789f2451-5a28-4633-ad36-4e85593dd302">

**Comment by okanduzyel** [comment]
By the way, I am using MacBook Air M2 machine.

**Comment by okanduzyel** [comment]
I think, everthing thing is okay in these foldiers. However, doesn't convert

<img width="1147" alt="Screenshot 2023-08-05 at 19 22 30" src="https://github.com/ggerganov/llama.cpp/assets/38145537/a248786f-888a-4a6c-a2f0-c7b157b3cafc">

**Comment by world1tree** [comment]
Try `python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 /Users/okanduzyel/llama2/meta_models/llama-2-7b-chat`.

**Comment by okanduzyel** [comment]
Doesn't work!

```
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 /Users/okanduzyel/llama2/meta_models/llama-2-7b-chat
Loading model file /Users/okanduzyel/llama2/meta_models/llama-2-7b-chat
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1319, in <module>
    main()
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1299, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1214, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1000, in lazy_load_file
    fp = open(path, 'rb')
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/okanduzyel/llama2/meta_models/llama-2-7b-chat'
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % 
```

**Comment by world1tree** [comment]
> I think, everthing is okay in these foldiers. However, doesn't convert
> 
> <img alt="Screenshot 2023-08-05 at 19 22 30" width="1147" src="https://user-images.githubusercontent.com/38145537/258596418-a248786f-888a-4a6c-a2f0-c7b157b3cafc.png">

Oh! From the image. The path should be `/Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat`, 
You might try `~/Downloads/llama2/meta_models/llama-2-7b-chat` or `/Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat`

**Comment by okanduzyel** [comment]
All of them didn't work...

```
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat
Loading model file /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat/consolidated.00.pth
vocabtype: spm
Loading vocab file /Users/okanduzyel/Downloads/llama2/meta_models/tokenizer.model
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1319, in <module>
    main()
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1307, in main
    vocab = load_vocab(vocab_dir, args.vocabtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1246, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 247, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: unk is not defined.
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 ~/Downloads/llama2/meta_models/llama-2-7b-chat
Loading model file /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat/consolidated.00.pth
vocabtype: spm
Loading vocab file /Users/okanduzyel/Downloads/llama2/meta_models/tokenizer.model
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1319, in <module>
    main()
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1307, in main
    vocab = load_vocab(vocab_dir, args.vocabtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1246, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 247, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: unk is not defined.
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat
Loading model file /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat/consolidated.00.pth
vocabtype: spm
Loading vocab file /Users/okanduzyel/Downloads/llama2/meta_models/tokenizer.model
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1319, in <module>
    main()
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1307, in main
    vocab = load_vocab(vocab_dir, args.vocabtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 1246, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/okanduzyel/Downloads/llama2/llama.cpp/convert.py", line 247, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/Ilama2/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: unk is not defined.
(Ilama2) (base) okanduzyel@Okans-MacBook-Air llama.cpp % python3 convert.py --outfile ~/models/7B/ggml-model-f16.bin --outtype f16 /Users/okanduzyel/Downloads/llama2/meta_models/llama-2-7b-chat

```

**Comment by VGSML** [comment]
I had same problem and it's helped: mkdir models/7B

**Comment by hstringa01** [comment]
> 

Were you able to get this working?

**Comment by Green-Sky** [comment]
you are missing the vocab/tokenizer.

**Comment by hstringa01** [comment]
I see the tokenizer.model in the downloaded llama directory from which is being called from.

**Comment by Green-Sky** [comment]
the tokenizer.model should be around 500kb

**Comment by KerfuffleV2** [comment]
> I see the tokenizer.model in the downloaded llama directory from which is being called from.

It'll only look in the model directory you specified. Your screenshot of the contents of that directory is missing those files.

Are you saying you have parts of the model in some other place?

**Comment by hstringa01** [comment]
I re-downloaded the tokenizer.model and seems to be good now. Thank you!
