### ISSUE TITLE
I am experiencing difficulties importing the llama_cpp package.

### ISSUE THREAD

**Issue by Hapluckyy** [ggerganov/llama.cpp#3291]
I have four A100 GPUs running in a supercomputing cluster and I have administrator privileges to log in to this cluster and access my computing resources.
I have successfully installed llama_cpp_python, but it seems that I am unable to use the package correctly.
# install llama_cpp_python

```
(gpu_llama) [root@gpu006 ~]# CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --verbose
Using pip 23.2.1 from /root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/pip (python 3.10)
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.6-cp310-cp310-manylinux_2_17_x86_64.whl
Requirement already satisfied: typing-extensions>=4.5.0 in ./anaconda3/envs/gpu_llama/lib/python3.10/site-packages (from llama-cpp-python) (4.8.0)
Requirement already satisfied: numpy>=1.20.0 in ./anaconda3/envs/gpu_llama/lib/python3.10/site-packages (from llama-cpp-python) (1.26.0)
Requirement already satisfied: diskcache>=5.6.1 in ./anaconda3/envs/gpu_llama/lib/python3.10/site-packages (from llama-cpp-python) (5.6.3)
Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.2.6
```

# Current environment
```
$ python --version 3.10.9
$ make --version    4.2.1
$ g++ --version      9.4.0
```

# Failure Logs

```
>>> from llama_cpp import Llama
Traceback (most recent call last):
  File "/root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 67, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
  File "/root/anaconda3/envs/gpu_llama/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 80, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 69, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/root/anaconda3/envs/gpu_llama/lib/python3.10/site-packages/llama_cpp/libllama.so': libcudart.so.11.0: cannot open shared object file: No such file or directory
```

I don't know why I am having this problem. Does this related to the supercomputing cluster?

I hope you know a solution !
Thanks in advance !

PS:I'm not very good in english, sorry(●'◡'●)

**Comment by deonis1** [comment]
Try looking for libcudart in your system, once found try exporting its location  
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.0/targets/x86_64-linux/lib
If you do not have the lib you will need to install cudnn. Also try installing llama.cpp by itself:
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp

sed -i 's/-arch=native/-arch=all/g' Makefile

make clean && LLAMA_CUBLAS=1 make -j

**Comment by Hapluckyy** [comment]
> @Hapluckyy Try looking for libcudart in your system, once found try exporting its location export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.0/targets/x86_64-linux/lib If you do not have the lib you will need to install cudnn. Also try installing llama.cpp by itself: git clone https://github.com/ggerganov/llama.cpp cd llama.cpp
> 
> sed -i 's/-arch=native/-arch=all/g' Makefile
> 
> make clean && LLAMA_CUBLAS=1 make -j
> 
> Do not want to struggle with python try this https://github.com/deonis1/llama.cui

Much appreciated, I tried to install llama.cui but I got some problems too
I ran 
```
make clean && LLAMA_CUBLAS=1 make -j
```
and it is not working, the logs are as follows:
```
I llama.cpp build info: 
I UNAME_S:   Linux
I UNAME_P:   x86_64
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native 
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native 
I NVCCFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread    -Wno-pedantic -Xcompiler "-march=native -mtune=native "
I LDFLAGS:    
I CC:        gcc (Spack GCC) 7.5.0
I CXX:       g++ (Spack GCC) 7.5.0

rm -vrf *.o tests/*.o *.so *.dll benchmark-matmult build-info.h *.dot *.gcno tests/*.gcno *.gcda tests/*.gcda *.gcov tests/*.gcov lcov-report gcovr-report main quantize quantize-stats perplexity embedding vdot train-text-from-scratch convert-llama2c-to-ggml simple save-load-state server embd-input-test gguf llama-bench baby-llama beam-search speculative tests/test-c.o metal tests/test-llama-grammar tests/test-grammar-parser tests/test-double-float tests/test-grad0 tests/test-opt tests/test-quantize-fns tests/test-quantize-perf tests/test-sampling tests/test-tokenizer-0-llama tests/test-tokenizer-0-falcon tests/test-tokenizer-1-llama
已删除"console.o"
已删除"ggml-alloc.o"
已删除"ggml.o"
已删除"grammar-parser.o"
已删除"k_quants.o"
已删除"llama.o"
已删除"tests/test-c.o"
已删除"build-info.h"
I llama.cpp build info: 
I UNAME_S:   Linux
I UNAME_P:   x86_64
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native 
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native 
I NVCCFLAGS: --forward-unknown-to-host-compiler -use_fast_math -arch=all -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128 -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread    -Wno-pedantic -Xcompiler "-march=native -mtune=native "
I LDFLAGS:   -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L/usr/local/cuda/lib64 -L/opt/cuda/lib64 -L/targets/x86_64-linux/lib 
I CC:        gcc (Spack GCC) 7.5.0
I CXX:       g++ (Spack GCC) 7.5.0

/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/gcc  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native    -c ggml.c -o ggml.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  -c llama.cpp -o llama.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  -c common/console.cpp -o console.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  -c common/grammar-parser.cpp -o grammar-parser.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/gcc -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native  -c k_quants.c -o k_quants.o
nvcc --forward-unknown-to-host-compiler -use_fast_math -arch=all -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128 -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread    -Wno-pedantic -Xcompiler "-march=native -mtune=native " -Wno-pedantic -c ggml-cuda.cu -o ggml-cuda.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/gcc  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native    -c ggml-alloc.c -o ggml-alloc.o
/nfs/opt/cascadelake/linux-centos7-cascadelake/gcc-9.4.0/gcc-7.5.0-yo7u6pt6g6xgd24rcj22cbhr42fjhdoz/bin/gcc -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native  -c tests/test-c.c -o tests/test-c.o
nvcc fatal   : Value 'all' is not defined for option 'gpu-architecture'
make: *** [ggml-cuda.o] 错误 1
make: *** 正在等待未完成的任务....





```

**Comment by deonis1** [comment]
@Hapluckyy try running nvcc --list-gpu-arch it should return your specific architecture, also nvidia-smi to see if driver installed correcly. But I think your problem with nvida cuda install. Also, your nvidia driver, cuda and cudnn releases must be compatible.

**Comment by deonis1** [comment]
@Hapluckyy Here is my ldd for llama.cpp/main executable: 
ldd ./main
	linux-vdso.so.1 (0x00007fffebdeb000)
	libcublas.so.11 => /lib/x86_64-linux-gnu/libcublas.so.11 (0x00007faaf5400000)
	libcudart.so.11.0 => /lib/x86_64-linux-gnu/libcudart.so.11.0 (0x00007faaf5000000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faaf4c00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faaffec1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faaffea1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faaf4800000)
	libcublasLt.so.11 => /lib/x86_64-linux-gnu/libcublasLt.so.11 (0x00007faadf200000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faaffe9a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007faaffe95000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faaffe90000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faafffc7000)
