### ISSUE TITLE
New models Sequelbox/StellarBright and ValiantLabs/ShiningValiant cannot be converted due to "Unexpected tensor name: model.layers.0.self_attn.q_proj.lora_A.default.weight"

### ISSUE THREAD

**Issue by TheBloke** [ggerganov/llama.cpp#3640]
The Open LLM Leaderboard is currently being lead by https://huggingface.co/ValiantLabs/ShiningValiant with https://huggingface.co/sequelbox/StellarBright in third place.

Unfortunately these models cannot be converted to GGUF, due to this error from `convert.py`:
```
Traceback (most recent call last):
  File "/workspace/git/gguf-llama/./convert.py", line 1193, in <module>
    main()
  File "/workspace/git/gguf-llama/./convert.py", line 1180, in main
    model   = convert_model_names(model, params)
  File "/workspace/git/gguf-llama/./convert.py", line 984, in convert_model_names
    raise Exception(f"Unexpected tensor name: {name}")
Exception: Unexpected tensor name: model.layers.0.self_attn.q_proj.lora_A.default.weight
```

Seems they have some kind of non-standard model layout here, which doesn't affect Transformers-based loading, but does break `convert.py`.

If anyone could find a fix or workaround, that'd be much appreciated - I'm getting quite a few requests for GGUFs of these models.

Here's the full output of `convert.py` on the base model, StellerBright:

```
 [venv] tomj@51e7fe45966e:/workspace/git/gguf-llama (master ✔) ᐅ python3 ./convert.py  --outtype f16 /workspace/process/sequelbox_stellarbright/source --outfile /workspace/process/sequelbox_stellarbright/gguf/stellarbright.fp16.gguf
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00001-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00001-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00002-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00003-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00004-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00005-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00006-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00007-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00008-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00009-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00010-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00011-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00012-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00013-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00014-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00015-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00016-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00017-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00018-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00019-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00020-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00021-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00022-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00023-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00024-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00025-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00026-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00027-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00028-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00029-of-00030.safetensors
Loading model file /workspace/process/sequelbox_stellarbright/source/model-00030-of-00030.safetensors
params = Params(n_vocab=32000, n_embd=8192, n_layer=80, n_ctx=4096, n_ff=28672, n_head=64, n_head_kv=8, f_norm_eps=1e-05, f_rope_freq_base=10000.0, f_rope_scale=None, ftype=<GGMLFileType.MostlyF16: 1>, path_model=PosixPath('/workspace/process/sequelbox_stellarbright/source'))
Loading vocab file '/workspace/process/sequelbox_stellarbright/source/tokenizer.model', type 'spm'
Permuting layer 0
Permuting layer 1
Permuting layer 2
Permuting layer 3
Permuting layer 4
Permuting layer 5
Permuting layer 6
Permuting layer 7
Permuting layer 8
Permuting layer 9
Permuting layer 10
Permuting layer 11
Permuting layer 12
Permuting layer 13
Permuting layer 14
Permuting layer 15
Permuting layer 16
Permuting layer 17
Permuting layer 18
Permuting layer 19
Permuting layer 20
Permuting layer 21
Permuting layer 22
Permuting layer 23
Permuting layer 24
Permuting layer 25
Permuting layer 26
Permuting layer 27
Permuting layer 28
Permuting layer 29
Permuting layer 30
Permuting layer 31
Permuting layer 32
Permuting layer 33
Permuting layer 34
Permuting layer 35
Permuting layer 36
Permuting layer 37
Permuting layer 38
Permuting layer 39
Permuting layer 40
Permuting layer 41
Permuting layer 42
Permuting layer 43
Permuting layer 44
Permuting layer 45
Permuting layer 46
Permuting layer 47
Permuting layer 48
Permuting layer 49
Permuting layer 50
Permuting layer 51
Permuting layer 52
Permuting layer 53
Permuting layer 54
Permuting layer 55
Permuting layer 56
Permuting layer 57
Permuting layer 58
Permuting layer 59
Permuting layer 60
Permuting layer 61
Permuting layer 62
Permuting layer 63
Permuting layer 64
Permuting layer 65
Permuting layer 66
Permuting layer 67
Permuting layer 68
Permuting layer 69
Permuting layer 70
Permuting layer 71
Permuting layer 72
Permuting layer 73
Permuting layer 74
Permuting layer 75
Permuting layer 76
Permuting layer 77
Permuting layer 78
Permuting layer 79
model.embed_tokens.weight                        -> token_embd.weight                        | F32    | [32000, 8192]
model.layers.0.input_layernorm.weight            -> blk.0.attn_norm.weight                   | F32    | [8192]
model.layers.0.mlp.down_proj.weight              -> blk.0.ffn_down.weight                    | F32    | [8192, 28672]
model.layers.0.mlp.gate_proj.weight              -> blk.0.ffn_gate.weight                    | F32    | [28672, 8192]
model.layers.0.mlp.up_proj.weight                -> blk.0.ffn_up.weight                      | F32    | [28672, 8192]
model.layers.0.post_attention_layernorm.weight   -> blk.0.ffn_norm.weight                    | F32    | [8192]
model.layers.0.self_attn.k_proj.weight           -> blk.0.attn_k.weight                      | F32    | [1024, 8192]
model.layers.0.self_attn.o_proj.weight           -> blk.0.attn_output.weight                 | F32    | [8192, 8192]
Traceback (most recent call last):
  File "/workspace/git/gguf-llama/./convert.py", line 1193, in <module>
    main()
  File "/workspace/git/gguf-llama/./convert.py", line 1180, in main
    model   = convert_model_names(model, params)
  File "/workspace/git/gguf-llama/./convert.py", line 984, in convert_model_names
    raise Exception(f"Unexpected tensor name: {name}")
Exception: Unexpected tensor name: model.layers.0.self_attn.q_proj.lora_A.default.weight
```

**Comment by mirek190** [comment]
Try this one 

https://github.com/ggerganov/llama.cpp/commit/34e5bd511dc9ac8942a662503a7e25db23c23e67

**Comment by TheBloke** [comment]
OK so as simple as skipping the layers?  Nice, I'll try it - thanks!

**Comment by TheBloke** [comment]
If the correct solution is to skip the lora_A tensors, what about adding it to `gguf-py/gguf/gguf.py` -> `MODEL_TENSOR_SKIP` ?

**Comment by TheBloke** [comment]
> I'm too tired to dig into it.

No worries, thanks for trying!

**Comment by slaren** [comment]
I don't see why the lora tensors would be needed in a merged model, it looks like an oversight that they are included in the model file at all.

**Comment by slaren** [comment]
This may work as a temporary solution, but I don't really know enough about the python code to tell if it is going to break something else:

```diff
diff --git a/convert.py b/convert.py
index e9b08d3..d27f466 100755
--- a/convert.py
+++ b/convert.py
@@ -979,6 +979,10 @@ def convert_model_names(model: LazyModel, params: Params) -> LazyModel:

     out: LazyModel = {}
     for name, lazy_tensor in model.items():
+        if "lora" in name:
+            print(f"skipping lora tensor {name}")
+            continue
+
         tensor_type, name_new = tmap.get_type_and_name(name, try_suffixes = (".weight", ".bias")) or (None, None)
         if name_new is None:
             raise Exception(f"Unexpected tensor name: {name}")
```

**Comment by TheBloke** [comment]
I've got it converting!  Thanks slaren just saw your fix, I'd already done my own similar hack:

```python
    for name, lazy_tensor in model.items():
        tensor_type, name_new = tmap.get_type_and_name(name, try_suffixes = (".weight", ".bias")) or (None, N
one)
        if name_new is None and 'lora_A' not in name and 'lora_B' not in name:
            raise Exception(f"Unexpected tensor name: {name}")

        if tensor_type in should_skip or 'lora_A' in name or 'lora_B' in name:
            print(f"skipping tensor {name_new}")
            continue

        print(f"{name:48s} -> {name_new:40s} | {lazy_tensor.data_type.name:6s} | {lazy_tensor.shape}")
        out[name_new] = lazy_tensor
```

Probably exactly the same end result as yours.  Fingers crossed..

**Comment by TheBloke** [comment]
I think we might be in business!
```
system_info: n_threads = 127 / 255 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


 The meaning of life is to find your gift. To give it away.
— David Viscott [end of text]

llama_print_timings:        load time =    2388.30 ms
llama_print_timings:      sample time =      11.59 ms /    17 runs   (    0.68 ms per token,  1466.66 tokens per second)
llama_print_timings: prompt eval time =    1093.47 ms /     6 tokens (  182.25 ms per token,     5.49 tokens per second)
llama_print_timings:        eval time =   14629.76 ms /    16 runs   (  914.36 ms per token,     1.09 tokens per second)
llama_print_timings:       total time =   15745.15 ms
Log end
```

Thanks all!
