### ISSUE TITLE
[Convert.py] when i convert the llama2-13b-chat model, i meet some problem

### ISSUE THREAD

**Issue by IronSpiderMan** [ggerganov/llama.cpp#3684]
this is my command:
```bash
python convert.py --outfile models/13B/gglm-model-f16.bin --outtype f16 G:/llama-2-13b-chat/
```
this is the error:
```python
Loading model file G:\llama-2-13b-chat\consolidated.00.pth
Traceback (most recent call last):
  File "G:\Workplace\llama.cpp\convert.py", line 1193, in <module>
    main()
  File "G:\Workplace\llama.cpp\convert.py", line 1134, in main
    model_plus = load_some_model(args.model)
  File "G:\Workplace\llama.cpp\convert.py", line 1054, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "G:\Workplace\llama.cpp\convert.py", line 744, in lazy_load_file
    elif struct.unpack('<Q', first8)[0] < 16 * 1024 * 1024:
struct.error: unpack requires a buffer of 8 bytes
```
i thought is ram problem, my environment is:
```
ram: 16G
GPU: rtx3060-laptop, 6G
```
does anyone know what's happened?

**Comment by shibe2** [comment]
Make sure you have actual large model files and not small text pointer files.
