### ISSUE TITLE
Convert consolidated pth files to gguf / missing script?

### ISSUE THREAD

**Issue by tsadrafoundation** [ggerganov/llama.cpp#4077]
I'm trying to run llama2 models on a mac M1 pro max

- I've downloaded the llama2 models with the link that was provided by email
- I've downloaded llama.cpp & compiled with make
- If I understand correctly llama.cpp needs the models to be converted to gguf (ggml?) format
- I see in the models only consolidated.00.pth files 
- I'm looking for the script `convert-pth-to-gguf.py` but it's not there

what am I missing?

I guess after this little step I can run 
```make -j && ./main -m models/llama-13b-v2/ggml-model-q4_0.gguf -p "Building a website can be done in 10 simple steps:\nStep 1:" -n 400 -e```

Version:
```
Python 3.11.6
GNU Make 3.81
Apple clang version 15.0.0 (clang-1500.0.40.1)
```

When i try to run:
```
python3 -m venv .env
source .env/bin/activate
pip install -r requirements.txt

python convert.py ../llama/llama-2-7b-chat
```

I get:
```
Loading model file ../llama/llama-2-7b-chat/consolidated.00.pth
Traceback (most recent call last):
  File "/Users/alex/dev/llama.cpp/convert.py", line 1207, in <module>
    main()
  File "/Users/alex/dev/llama.cpp/convert.py", line 1140, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 1055, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 740, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: ../llama/llama-2-7b-chat/consolidated.00.pth
```

**Comment by huawei-lin** [comment]
Did you check your .pth file is correct?
The file should be 13.5GB.

**Comment by tsadrafoundation** [comment]
Hi @huawei-lin,

the 7b model is:
```
 llama-2-7b % du -hs *
584K	checklist.chk
 13G	consolidated.00.pth
584K	params.json
```

The 13b model is:
```
(.env) alex@MacBook-Pro llama-2-13b % ls -l
total 50847376
-rw-r--r--  1 alex  staff       594145 Nov  9 09:05 checklist.chk
-rw-r--r--  1 alex  staff  13016329643 Jul 13 19:12 consolidated.00.pth
-rw-r--r--  1 alex  staff  13016329643 Jul 13 19:12 consolidated.01.pth
-rw-r--r--  1 alex  staff       594043 Nov  9 09:05 params.json
(.env) alex@MacBook-Pro llama-2-13b % du -hs *
584K	checklist.chk
 12G	consolidated.00.pth
 12G	consolidated.01.pth
584K	params.json
```
Then there's the 70b model

**Comment by tsadrafoundation** [comment]
Actually the chat models are not even 1 MB, that must be the issue.

but if I run:
```
python convert.py ../llama/llama-2-7b
Loading model file ../llama/llama-2-7b/consolidated.00.pth
Traceback (most recent call last):
  File "/Users/alex/dev/llama.cpp/convert.py", line 1207, in <module>
    main()
  File "/Users/alex/dev/llama.cpp/convert.py", line 1151, in main
    params = Params.load(model_plus)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 278, in load
    params = Params.loadOriginalParamsJson(model_plus.model, orig_config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 245, in loadOriginalParamsJson
    config = json.load(open(config_path))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 102)
```

This is another issue

**Comment by huawei-lin** [comment]
As listed in https://huggingface.co/meta-llama/Llama-2-7b-chat/tree/main . the chat 7b should be 13G.
Your 7b model seems no problem, did you meet the same issue with the 7b model?

**Comment by huawei-lin** [comment]
@tsadrafoundation For the JSONDecodeError, could you check your param.json of the 7b model?
It should be
```
{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-05, "vocab_size": -1}
```
https://huggingface.co/meta-llama/Llama-2-7b/blob/main/params.json

**Comment by tsadrafoundation** [comment]
So it starts like that but there's much more:
```
llama-2-7b % cat params.json 
{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-05, "vocab_size": -1}
<meta name="referrer" content="origin"><style data-href="https://www.gstatic.com/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.wx0CABSJ-es.L.W.O/am=DoQVkTk2AIX_A6AAgABAgQIAAAAAAAgAANBAlhA/d=1/ed=1/rs=AOaEmlHU6nuQZPpB-_Fypm8p8GnU0AgdSw/m=identifierview,_b,_tp" nonce="vvHbjiuKJRE2iT74tRCAwQ">c-wiz{contain:style}c-wiz>c-data{display:none}c-wiz.rETSD{contain:none}c-wiz.Ubi8Z{contain:layout style}@-webkit-keyframes quantumWizBoxInkSpread{0%{-webkit-transform:translate(-50%,-50%) scale(0.2);-webkit-transform:translate(-50%,-50%) scale(0.2);transform:translate(-50%,-50%) scale(0.2)}to{-webkit-transform:translate(-50%,-50%) scale(2.2);-webkit-transform:translate(-50%,-50%) scale(2.2);transform:translate(-50%,-50%) scale(2.2)}}@keyframes quantumWizBoxInkSprea ...
```
is this normal ?

**Comment by Galunid** [comment]
No it's not. It seems your file was corrupted. Try deleting the last line `<meta ...`

**Comment by huawei-lin** [comment]
This should be the problem. It should be 84 bytes.

**Comment by tsadrafoundation** [comment]
now I'm getting this:
```
 python convert.py ../llama/llama-2-7b
Loading model file ../llama/llama-2-7b/consolidated.00.pth
params = Params(n_vocab=-1, n_embd=4096, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=PosixPath('../llama/llama-2-7b'))
Loading vocab file '../llama/tokenizer.model', type 'spm'
Traceback (most recent call last):
  File "/Users/alex/dev/llama.cpp/convert.py", line 1207, in <module>
    main()
  File "/Users/alex/dev/llama.cpp/convert.py", line 1187, in main
    vocab = load_vocab(vocab_dir, args.vocabtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 1087, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/convert.py", line 350, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/.env/lib/python3.11/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/Users/alex/dev/llama.cpp/.env/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/dev/llama.cpp/.env/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: /Users/runner/work/sentencepiece/sentencepiece/src/sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```

**Comment by kaycebasques** [comment]
Just encountered this. The root cause in my case was putting in the wrong value for the first step in LLaMa's download script. You're supposed to put in the link from the email but I accidentally put in my actual email address. `params.json` was full of HTML because Meta was essentially denying my download request. As others have said, just delete the failed download directory and start over.
