### ISSUE TITLE
Finetuning on AMD GPU

### ISSUE THREAD

**Issue by fakerybakery** [ggerganov/llama.cpp#4109]
Can we finetune this on an AMD GPU?

**Comment by KerfuffleV2** [comment]
It should work the same as CUDA.

**Comment by bog-dan-ro** [comment]
For me it crashes :
```
$ ./finetune --model-base llama-2-7b-chat.Q4_K_M.gguf --lora-out lora-llama-2-7b-chat.Q4_K_M.gguf --train-data "shakespeare.txt" --adam-iter 30 --threads 1 --batch 4 --ctx 64  -ngl 35
...
src0->type: 14  dst->type: 0
GGML_ASSERT: ggml-cuda.cu:6158: false
[New LWP 44303]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f31670ea42f in __GI___wait4 (pid=44306, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x00007f31670ea42f in __GI___wait4 (pid=44306, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00005642243afa8b in ggml_print_backtrace ()
#2  0x0000564224481535 in ggml_cuda_op_add(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, float const*, float const*, float*, ihipStream_t* const&) ()
#3  0x000056422447671d in ggml_cuda_op_flatten(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, void (*)(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, float const*, float const*, float*, ihipStream_t* const&)) ()
#4  0x00005642244706a7 in ggml_cuda_compute_forward ()
#5  0x00005642243dd998 in ggml_graph_compute_thread ()
#6  0x00005642243e1b98 in ggml_graph_compute ()
#7  0x00005642243e4b3e in ggml_opt_adam ()
#8  0x00005642243e7fc6 in ggml_opt_resume_g ()
#9  0x00005642243a0bcf in main ()
[Inferior 1 (process 44302) detached]
```

**Comment by KerfuffleV2** [comment]
I can reproduce this on the latest master. Offloading any number of layers results in that assert failing.

The ROCM stuff uses the CUDA backend so basically what works for Nvidia cards should work for AMD cards. It was already supposed to work (as far as I know), so this is actually a bug.
