### ISSUE TITLE
Unexpected tensor name: layers.4.block_sparse_moe.gate.weight when converting 7*8B mixtral model 

### ISSUE THREAD

**Issue by yw2278** [ggerganov/llama.cpp#4523]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I used the script mentioned in https://github.com/ggerganov/llama.cpp/pull/4406
```python
python3 convert.py ./models/mixtral-instruct-8x7b/ \
         --outfile ./models/mixtral-instruct-8x7b/ggml-model-f16.gguf \
         --outtype f16
```
expected to convert to gguf model

# Current Behavior

convert script throw an error **Unexpected tensor name: layers.4.block_sparse_moe.gate.weight** 
it seems that in convert.py 1066
```python
tensor_type, name_new = tmap.get_type_and_name(name, try_suffixes = (".weight", ".bias")) or (None, None)
```
get_type_and_name cannot recognize layers.4.block_sparse_moe.gate.weight which I checked is legit part in mixtral model.
Is this a bug?

**Comment by adamluzsi** [comment]
I'm not sure if this is the same, but I have a similar error running the `convert.py`:

```
$ python3 llama.cpp/convert.py ./models/Mixtral-8x7B-Instruct-v0.1/ --outfile ./models/Mixtral-8x7B-Instruct-v0.1/ggml-model-f32.gguf --outtype f32
```

<details>
  <summary>**output**</summary>

```
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00001-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00001-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00002-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00003-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00004-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00005-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00006-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00007-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00008-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00009-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00010-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00011-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00012-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00013-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00014-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00015-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00016-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00017-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00018-of-00019.safetensors
Loading model file models/Mixtral-8x7B-Instruct-v0.1/model-00019-of-00019.safetensors
params = Params(n_vocab=32000, n_embd=4096, n_layer=32, n_ctx=32768, n_ff=14336, n_head=32, n_head_kv=8, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=1000000.0, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=<GGMLFileType.AllF32: 0>, path_model=PosixPath('models/Mixtral-8x7B-Instruct-v0.1'))
Loading vocab file 'models/Mixtral-8x7B-Instruct-v0.1/tokenizer.model', type 'spm'
Permuting layer 0
Permuting layer 1
Permuting layer 2
Permuting layer 3
Permuting layer 4
Permuting layer 5
Permuting layer 6
Permuting layer 7
Permuting layer 8
Permuting layer 9
Permuting layer 10
Permuting layer 11
Permuting layer 12
Permuting layer 13
Permuting layer 14
Permuting layer 15
Permuting layer 16
Permuting layer 17
Permuting layer 18
Permuting layer 19
Permuting layer 20
Permuting layer 21
Permuting layer 22
Permuting layer 23
Permuting layer 24
Permuting layer 25
Permuting layer 26
Permuting layer 27
Permuting layer 28
Permuting layer 29
Permuting layer 30
Permuting layer 31
model.embed_tokens.weight                        -> token_embd.weight                        | BF16   | [32000, 4096]
Traceback (most recent call last):
  File "llama.cpp/convert.py", line 1228, in <module>
    main()
  File "llama.cpp/convert.py", line 1215, in main
    model   = convert_model_names(model, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llama.cpp/convert.py", line 1004, in convert_model_names
    raise Exception(f"Unexpected tensor name: {name}")
Exception: Unexpected tensor name: model.layers.0.block_sparse_moe.experts.0.w1.weight
```
</details>

**Comment by cheesgno** [comment]
I have the same issue.
Could it depend to llama.cpp version?

**Comment by adamluzsi** [comment]
I pulled the latest main, and the converting works again for me. 🙌

**Comment by ehlowr0ld** [comment]
Not here, latest master still no convert - same error :(

**Comment by ehlowr0ld** [comment]
```
Traceback (most recent call last):
  File "/home/llmplatform/repos/llama.cpp/models/convert/convert.py", line 1279, in <module>
    main()
  File "/home/llmplatform/repos/llama.cpp/models/convert/convert.py", line 1265, in main
    model   = convert_model_names(model, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llmplatform/repos/llama.cpp/models/convert/convert.py", line 1068, in convert_model_names
    raise Exception(f"Unexpected tensor name: {name}")
Exception: Unexpected tensor name: model.layers.0.block_sparse_moe.gate.weight
```

**Comment by ehlowr0ld** [comment]
I must admit that i was until now always using convert.py, i will try the convert-hf-to-gguf.

**Comment by ehlowr0ld** [comment]
No luck either, completely different error
```
gguf: This GGUF file is for Little Endian only
Set model parameters
Traceback (most recent call last):
  File "/home/llmplatform/repos/llama.cpp/models/convert/convert-hf-to-gguf.py", line 1058, in <module>
    model_instance.set_gguf_parameters()
  File "/home/llmplatform/repos/llama.cpp/models/convert/convert-hf-to-gguf.py", line 88, in set_gguf_parameters
    self.gguf_writer.add_expert_count(n_experts)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GGUFWriter' object has no attribute 'add_expert_count'. Did you mean: 'add_head_count'?
```

**Comment by ehlowr0ld** [comment]
^^ Forget my posts, seems like symlinking the script was my fault, i did not notice it had relative includes and probably picked something global instead of local poetry venv

**Comment by yw2278** [comment]
I used pt model files before, it seems that **mixtral pt model index is different from safetensor index.**
