### ISSUE TITLE
Getting the following bug when running running convert.py

### ISSUE THREAD

**Issue by chetan-guevara** [ggerganov/llama.cpp#4945]
I have a Mac M3 

After running "make", I ran the following:
`python3 convert.py  --outfile models/ggml-model-7b-chat-f16.bin  --outtype f16 ../llama/llama-2-7b-chat"`

I Got the following error:
```
Writing models/ggml-model-7b-chat-f16.bin, format 1
Traceback (most recent call last):
  File "/Users/chetan/Dropbox/Code/llama.cpp/convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "/Users/chetan/Dropbox/Code/llama.cpp/convert.py", line 1643, in main
    OutputFile.write_all(
  File "/Users/chetan/Dropbox/Code/llama.cpp/convert.py", line 1188, in write_all
    check_vocab_size(params, vocab, pad_vocab=pad_vocab)
  File "/Users/chetan/Dropbox/Code/llama.cpp/convert.py", line 993, in check_vocab_size
    raise ValueError(
ValueError: The model's vocab size is set to -1 in params.json. Please update it manually. Maybe 32000?
```

Any ideas as to how to fix this?

**Comment by chetan-guevara** [comment]
Looking at other threads, the solution was to revert to an older commit:

git checkout 0353a1840134b24b07ab61fd4490192f28c4db6b
