### ISSUE TITLE
GPT-2 support converting to GGUF?

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#5032]
I see GPT2 is supported in the list. However, when I try to convert the GPT-2 safetensors to GGUF, I get this error:

```
Loading model file /mnt/m2_4tb/text-generation-webui/models/gpt2/model.safetensors
Traceback (most recent call last):
  File "/mnt/m2_4tb/llama.cpp/convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "/mnt/m2_4tb/llama.cpp/convert.py", line 1591, in main
    params = Params.load(model_plus)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/m2_4tb/llama.cpp/convert.py", line 370, in load
    params = Params.load_transformers_config(model_plus.model, hf_config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/m2_4tb/llama.cpp/convert.py", line 287, in load_transformers_config
    raise Exception(
Exception: failed to guess 'n_ctx'. This model is unknown or unsupported.
Suggestion: provide 'config.json' of the model in the same directory containing model files.
```

How can I use GPT-2 models with llama.cpp?

**Comment by BarfingLemurs** [comment]
@l3utterfly Try converting non-safetensors version: 
https://huggingface.co/gpt2/blob/main/pytorch_model.bin

**Comment by l3utterfly** [comment]
@BarfingLemurs hmm.. still getting some errors:

```
(.venv) PS C:\src\l3utterfly\llama.cpp> python convert.py "C:/Users/gcpth/Downloads/gpt2"
C:\src\l3utterfly\llama.cpp\gguf-py
Loading model file C:\Users\gcpth\Downloads\gpt2\pytorch_model.bin
Traceback (most recent call last):
  File "C:\src\l3utterfly\llama.cpp\convert.py", line 1662, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
    ^^^^^^^^^^^^^^^^^^
  File "C:\src\l3utterfly\llama.cpp\convert.py", line 1581, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\l3utterfly\llama.cpp\convert.py", line 1357, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\src\l3utterfly\llama.cpp\convert.py", line 950, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: C:\Users\gcpth\Downloads\gpt2\pytorch_model.bin
```

**Comment by BarfingLemurs** [comment]
Ah, use the `convert-hf-to-gguf.py` script instead, on the safetensors model. That worked.

**Comment by l3utterfly** [comment]
Thank you! that worked
