### ISSUE TITLE
Help: FileNotFoundError: spm vocab not found

### ISSUE THREAD

**Issue by xjj210130** [ggerganov/llama.cpp#5135]
I do the following steps:
1:  https://github.com/ggerganov/llama.cpp.git
2:  pip3 install -r requirements.txt
3:  download the facebook llama2-7b  model
4:   python3 convert.py /work/llama.cpp/models/7b  --outfile /work/llama.cpp/out_7b/ggml-model-f16.gguf  --outtype f16
but , it can't works. There is following wrong:
```
Loading model file /work/llama.cpp/models/7b/consolidated.00.pth
params = Params(n_vocab=32000, n_embd=4096, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, n_experts=None, n_experts_used=None, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=<GGMLFileType.MostlyF16: 1>, path_model=PosixPath('/work/llama.cpp/models/7b'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': None, 'tokenizer.json': None}
Traceback (most recent call last):
  File "/work/llama.cpp/convert.py", line 1471, in <module>
    main()
  File "/work/llama.cpp/convert.py", line 1439, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
  File "/work/llama.cpp/convert.py", line 1315, in load_vocab
    path = self._select_file(vocabtype)
  File "/work/llama.cpp/convert.py", line 1298, in _select_file
    raise FileNotFoundError(f"{vocabtype} vocab not found.")
FileNotFoundError: spm vocab not found.
```

My env is :  5.15.133.1-microsoft-standard-WSL2
python 3.9.10
g++ 11.4.0
no gpu

I don't find the file tokenizer_checklist.ch and tokenizer.model when i clone the llama project.
Thanks.

**Comment by singhaki** [comment]
you need to have tokenizer file in the model repo and add param --vocab-type hfft for huggingface transformers tokenizer
