### ISSUE TITLE
Getting llama_model_load: error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape on Inference using the custom model of TinyLlama

### ISSUE THREAD

**Issue by UYousafzai** [ggerganov/llama.cpp#5367]
### Using the TinyLlama chat v1.0 model that was finetuned on custom data.
the conversion goes through smoothly however I start getting this error when I try to load the model, now this wasn't an issue before updating my llama-cpp-python library which I did and then I started getting this error, is there a possibility that the error is due to a mismatch version between the acutal llama.cpp and what llama-cpp-python is trying to use? 

###  Trace

llama_model_load: error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  2048,  2048, got  2048,   256,     1,     1
llama_load_model_from_file: failed to load model
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    from executor import METHOD_MAPPING
  File "/home/umar/Documents/code/inference/executor.py", line 14, in <module>
    from llmt2 import PIPELINE_MAPPING
  File "/home/umar/Documents/code/inference/llmt2/__init__.py", line 5, in <module>
    from .executor import DefaultPipelineExecutor
  File "/home/umar/Documents/code/inference/llmt2/executor.py", line 4, in <module>
    from .lcpp import default_pipeline
  File "/home/umar/Documents/code/inference/llmt2/lcpp/__init__.py", line 15, in <module>
    default_pipeline = Pipeline(model_path="./llmt2/lcpp/models/gguf/ggml-model-f16.gguf")
  File "/home/umar/Documents/code/inference/llmt2/lcpp/pipeline.py", line 35, in __init__
    self.ner = NamedEntityRecognition(model_path, n_ctx)
  File "/home/umar/Documents/code/inference/llmt2/lcpp/recogniser.py", line 19, in __init__
    self.llm = Llama(model_path=model_path, n_ctx=n_ctx)
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/llama_cpp/llama.py", line 327, in __init__
    self._n_vocab = self.n_vocab()
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/llama_cpp/llama.py", line 1693, in n_vocab
    return self._model.n_vocab()
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/llama_cpp/_internals.py", line 67, in n_vocab
    assert self.model is not None
AssertionError

**Comment by UYousafzai** [comment]
The conversion script lands in the guessed model params and makes incorrect guessing leading to incorrect layer shapes, causing the error during inference.
