### ISSUE TITLE
convert-hf-to-gguf.py has broken Persimmon support

### ISSUE THREAD

**Issue by cebtenzzre** [ggerganov/llama.cpp#5667]
[persimmon-8b-chat](https://huggingface.co/adept/persimmon-8b-chat) from HF fails to convert with this error:
```
$ ./convert-hf-to-gguf.py ~/dirs/text-ai-models/dl/persimmon-8b-chat --outfile ~/dirs/text-ai-models/unquant/persimmon-8b-chat.f16.gguf --outtype f16
Loading model: persimmon-8b-chat
gguf: This GGUF file is for Little Endian only
Set model parameters
Traceback (most recent call last):
  File "/home/jared/src/forks/llama.cpp/convert-hf-to-gguf.py", line 1876, in <module>
    main()
  File "/home/jared/src/forks/llama.cpp/convert-hf-to-gguf.py", line 1860, in main
    model_instance.set_gguf_parameters()
  File "/home/jared/src/forks/llama.cpp/convert-hf-to-gguf.py", line 1034, in set_gguf_parameters
    self.gguf_writer.add_layer_norm_rms_eps(self.hparams["rms_norm_eps"])
                                            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'rms_norm_eps'
```

It does special-case PersimmonForCausalLM, so there is supposed to be support, it just doesn't work.

**Comment by ggerganov** [comment]
It should be a simple fix, since rms norm is not used in Orion arch:

```diff
diff --git a/convert-hf-to-gguf.py b/convert-hf-to-gguf.py
index 9771fccf..5e17d6e2 100755
--- a/convert-hf-to-gguf.py
+++ b/convert-hf-to-gguf.py
@@ -1031,7 +1031,6 @@ class PersimmonModel(Model):
         self.gguf_writer.add_head_count_kv(head_count_kv)
         self.gguf_writer.add_rope_freq_base(self.hparams["rope_theta"])
         self.gguf_writer.add_layer_norm_eps(self.hparams["layer_norm_eps"])
-        self.gguf_writer.add_layer_norm_rms_eps(self.hparams["rms_norm_eps"])
 
     def set_vocab(self):
         self._set_vocab_sentencepiece()
```
