### ISSUE TITLE
Gemma models quantized using llamacpp not working in lm studio

### ISSUE THREAD

**Issue by rombodawg** [ggerganov/llama.cpp#5706]
Gemma models that have been quantized using Llamacpp are not working. Please look into the issue

error

"llama.cpp error: 'create_tensor: tensor 'output.weight' not found'"

I will open a issue on the lm studio github aswell addressing this

https://github.com/lmstudio-ai/configs/issues/21

**Comment by Yefori-Go** [comment]
![image](https://github.com/ggerganov/llama.cpp/assets/110314400/41433911-8e6a-438f-9e64-2ae5694502eb)
Perhaps you should try using the latest llama.cpp to convert gemma model.

` python .\convert-hf-to-gguf.py models\gemma-2b-it\ --outfile gemma-2b-it-f16.gguf`

**Comment by JohannesGaessler** [comment]
I can only speak for myself but I 100% refuse to debug a problem unless it can be reproduced entirely with open-source code.

**Comment by rombodawg** [comment]
No it literally doesnt work

I just built this version of llamacpp. And that .py script doesnt work for Gemma

```
NotImplementedError: Architecture "GemmaForCausalLM" not supported!
```

```
E:\Open_source_ai_chatbot\Llamacpp-3\llama.cpp>python E:\Open_source_ai_chatbot\Llamacpp-mixtral\llamacpp-clone-mixtral\convert-hf-to-gguf.py E:\Open_source_ai_chatbot\OOBA_10\text-generation-webui-main\models\Gemma-EveryoneLLM-7b-test --outfile Gemma-EveryoneLLM-7b-test.gguf --outtype f16
Loading model: Gemma-EveryoneLLM-7b-test
Traceback (most recent call last):
  File "E:\Open_source_ai_chatbot\Llamacpp-mixtral\llamacpp-clone-mixtral\convert-hf-to-gguf.py", line 1033, in <module>    model_instance = model_class(dir_model, ftype_map[args.outtype], fname_out, args.bigendian)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Open_source_ai_chatbot\Llamacpp-mixtral\llamacpp-clone-mixtral\convert-hf-to-gguf.py", line 48, in __init__
    self.model_arch = self._get_model_architecture()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Open_source_ai_chatbot\Llamacpp-mixtral\llamacpp-clone-mixtral\convert-hf-to-gguf.py", line 225, in _get_model_architecture
    raise NotImplementedError(f'Architecture "{arch}" not supported!')
NotImplementedError: Architecture "GemmaForCausalLM" not supported!
```

**Comment by rombodawg** [comment]
@JohannesGaessler I totally understand that, hopefully openai is willing to reach out and work with you to fix this

**Comment by hiepxanh** [comment]
@rombodawg  did you try latest version? 
https://github.com/ggerganov/llama.cpp/issues/6051

**Comment by DementedWeasel1971** [comment]
I think like me people are considering other options.  I will however keep on watching the release notes to see when this is fixed.
