### ISSUE TITLE
Vulkan backend: GGML_ASSERT: ggml-vulkan.cpp:3063: src1 == nullptr || ggml_vk_dim01_contiguous(src1) when offloading gpu layers

### ISSUE THREAD

**Issue by 890m319as** [ggerganov/llama.cpp#5787]
GPU: AMD Radeon RX 5700 XT (RADV NAVI10) (8gb vram)
Model: mistralai_mixtral-8x7b-instruct-v0.1 Q4_K_M quant (can't link because huggingface is down)
whenever -ngl isn't zero, crashes with this backtrace.

I used `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`

so it would actually give a trace

log:
```
❯ ./main -m mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -ngl 5 -c 8096
Log start
main: build = 288 (87c91c0)
main: built with cc (GCC) 13.2.1 20230801 for x86_64-pc-linux-gnu
main: seed  = 1709170957
ggml_vulkan: Found 1 Vulkan devices:
Vulkan0: AMD Radeon RX 5700 XT (RADV NAVI10) | uma: 0 | fp16: 1 | warp size: 64
llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mixtral-8x7b-instruct-v0.1
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 15
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q4_K:  833 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 24.62 GiB (4.53 BPW) 
llm_load_print_meta: general.name     = mistralai_mixtral-8x7b-instruct-v0.1
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.76 MiB
llm_load_tensors: offloading 5 repeating layers to GPU
llm_load_tensors: offloaded 5/33 layers to GPU
llm_load_tensors:        CPU buffer size = 25215.87 MiB
llm_load_tensors:    Vulkan0 buffer size =  3912.97 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 8096
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: Vulkan_Host KV buffer size =   853.88 MiB
llama_kv_cache_init:    Vulkan0 KV buffer size =   158.12 MiB
llama_new_context_with_model: KV self size  = 1012.00 MiB, K (f16):  506.00 MiB, V (f16):  506.00 MiB
llama_new_context_with_model: Vulkan_Host input buffer size   =    24.89 MiB
llama_new_context_with_model:    Vulkan0 compute buffer size =   581.82 MiB
llama_new_context_with_model: Vulkan_Host compute buffer size =   566.03 MiB
llama_new_context_with_model: graph splits (measure): 3
GGML_ASSERT: ggml-vulkan.cpp:3063: src1 == nullptr || ggml_vk_dim01_contiguous(src1)
[New LWP 1466699]
[New LWP 1466700]
[New LWP 1466701]
[New LWP 1466702]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fada290fec7 in __GI___wait4 (pid=1466727, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30        return SYSCALL_CANCEL (wait4, pid, stat_loc, options, usage);
#0  0x00007fada290fec7 in __GI___wait4 (pid=1466727, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30        return SYSCALL_CANCEL (wait4, pid, stat_loc, options, usage);
#1  0x000055acbdaed30b in ggml_print_backtrace ()
#2  0x000055acbdbff1d1 in void ggml_vk_op_f32<vk_op_push_constants>(ggml_backend_vk_context*, vk_context*, ggml_tensor const*, ggml_tensor const*, ggml_tensor*, ggml_op, vk_op_push_constants const&&) ()
#3  0x000055acbdc00a8e in ggml_vk_build_graph(ggml_backend_vk_context*, ggml_tensor*, bool) ()
#4  0x000055acbdc0323b in ggml_backend_vk_graph_compute(ggml_backend*, ggml_cgraph*) ()
#5  0x000055acbdc1936b in ggml_backend_sched_graph_compute ()
#6  0x000055acbdb5f164 in llama_decode ()
#7  0x000055acbdba8196 in llama_init_from_gpt_params(gpt_params&) ()
#8  0x000055acbdae608c in main ()
[Inferior 1 (process 1466698) detached]
zsh: IOT instruction (core dumped)  ./main -m mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -ngl 5 -c 8096
```

**Comment by Jacoby1218** [comment]
Mixtral isn't supported on Vulkan ATM.

**Comment by 890m319as** [comment]
Okay.
