### ISSUE TITLE
Unable to convert phi-2 model

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#5812]
It says Phi models are supported in the ReadMe, but I'm having trouble converting them to GGUF. The microsoft released one: `https://huggingface.co/microsoft/phi-2`

I'm getting the following error on the latest main branch:
```
(llamacpp) layla@purplerain:~/src/llama.cpp$ python convert.py /home/layla/src/text-generation-webui/models/phi-2
Loading model file /home/layla/src/text-generation-webui/models/phi-2/model-00001-of-00002.safetensors
Loading model file /home/layla/src/text-generation-webui/models/phi-2/model-00001-of-00002.safetensors
Loading model file /home/layla/src/text-generation-webui/models/phi-2/model-00002-of-00002.safetensors
Traceback (most recent call last):
  File "/home/layla/src/llama.cpp/convert.py", line 1483, in <module>
    main()
  File "/home/layla/src/llama.cpp/convert.py", line 1430, in main
    params = Params.load(model_plus)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/layla/src/llama.cpp/convert.py", line 317, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/layla/src/llama.cpp/convert.py", line 256, in loadHFTransformerJson
    f_norm_eps        = config["rms_norm_eps"],
                        ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'rms_norm_eps'
```

**Comment by ggerganov** [comment]
Use `convert-hf-to-gguf.py` instead of `convert.py`

**Comment by l3utterfly** [comment]
Thank you! That works!
