### ISSUE TITLE
convert.py incompatible with most new models, including salesforce/codegen models

### ISSUE THREAD

**Issue by Raptor85** [ggerganov/llama.cpp#6030]
Most newer models on huggingface are unable to be converted with convert.py, including all the Salesforce/codegen, Salesforce/codegen2, and Salesforce/codegen25 models. Examples of output of different salesforce models below

### codegen25-7b-multi
https://huggingface.co/Salesforce/codegen25-7b-multi
```
(pythonenv) raptor85@raptor1 /var/storage/llama/llama.cpp $ python convert.py huggingface/Salesforce/codegen25-7b-multi --outfile models/salesforce-codegen25-7b-multi.gguf --outtype f16
Loading model file huggingface/Salesforce/codegen25-7b-multi/pytorch_model-00001-of-00003.bin
Loading model file huggingface/Salesforce/codegen25-7b-multi/pytorch_model-00001-of-00003.bin
Loading model file huggingface/Salesforce/codegen25-7b-multi/pytorch_model-00002-of-00003.bin
Loading model file huggingface/Salesforce/codegen25-7b-multi/pytorch_model-00003-of-00003.bin
params = Params(n_vocab=51200, n_embd=4096, n_layer=32, n_ctx=2048, n_ff=11008, n_head=32, n_head_kv=32, n_experts=None, n_experts_used=None, f_norm_eps=1e-06, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=<GGMLFileType.MostlyF16: 1>, path_model=PosixPath('huggingface/Salesforce/codegen25-7b-multi'))
Found vocab files: {'spm': None, 'bpe': None, 'hfft': None}
Traceback (most recent call last):
  File "/var/storage/llama/llama.cpp/convert.py", line 1466, in <module>
    main()
  File "/var/storage/llama/llama.cpp/convert.py", line 1434, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type.split(","), model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 1323, in load_vocab
    vocab_type, path = self._select_file(vocab_types)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 1310, in _select_file
    raise FileNotFoundError(f"Could not find any of {[self._FILES[vt] for vt in vocab_types]}")
FileNotFoundError: Could not find any of ['tokenizer.model', 'tokenizer.json']
```

### codegen2-7b
https://huggingface.co/Salesforce/codegen2-7B
```
(pythonenv) raptor85@raptor1 /var/storage/llama/llama.cpp $ python convert.py huggingface/Salesforce/codegen2-7B --outfile models/salesforce-codegen2-7b.gguf --outtype f16
Loading model file huggingface/Salesforce/codegen2-7B/pytorch_model-00001-of-00003.bin
Traceback (most recent call last):
  File "/var/storage/llama/llama.cpp/convert.py", line 1466, in <module>
    main()
  File "/var/storage/llama/llama.cpp/convert.py", line 1402, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 1278, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 887, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 843, in lazy_load_torch_file
    model = unpickler.load()
            ^^^^^^^^^^^^^^^^
  File "/var/storage/llama/llama.cpp/convert.py", line 832, in find_class
    return self.CLASSES[(module, name)]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: ('torch', 'ByteStorage')
```

### Installed python packages
```
Package                  Version
------------------------ ----------
certifi                  2024.2.2
charset-normalizer       3.3.2
einops                   0.7.0
filelock                 3.13.1
fsspec                   2024.2.0
gguf                     0.6.0
huggingface-hub          0.21.4
idna                     3.6
Jinja2                   3.1.3
MarkupSafe               2.1.5
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.4.99
nvidia-nvtx-cu12         12.1.105
packaging                24.0
pip                      24.0
protobuf                 4.25.3
PyYAML                   6.0.1
regex                    2023.12.25
requests                 2.31.0
safetensors              0.4.2
sentencepiece            0.1.99
setuptools               69.0.3
sympy                    1.12
tiktoken                 0.4.0
tokenizers               0.15.2
torch                    2.1.2
tqdm                     4.66.2
transformers             4.38.2
triton                   2.1.0
typing_extensions        4.10.0
urllib3                  2.2.1
```

**Comment by tau0-deltav** [comment]
These models aren't new at all, Codegen 2 was released [nearly a year ago](https://huggingface.co/Salesforce/codegen2-7B/commit/9aaa0ce5dd93b682f3c7fd9a6577faa0417dbf6c). [This paper](https://arxiv.org/abs/2305.02309) is from 03 May 2023. they're using weirdo python scripts for custom tokenisers (and no actual list-of-tokens in plain sight) and _they're not `safetensors`_

You're looking at the "updated" date :) 

[Starcoder](https://huggingface.co/bigcode/starcoder2-7b) is pretty hot right now.
