### ISSUE TITLE
Im getting this error while trying to convert .pth to .bin

### ISSUE THREAD

**Issue by Shreyas-ITB** [ggerganov/llama.cpp#659]
**Error that im getting**

`shreyas@ATLAS-AHQVOLJ9A:/mnt/c/Users/Shreyas-ITB/Downloads/llama.cpp$ python3 convert-pth-to-ggml.py models/7B/ 1
{'dim': 4096, 'multiple_of': 256, 'n_heads': 32, 'n_layers': 32, 'norm_eps': 1e-06, 'vocab_size': -1}
Namespace(dir_model='models/7B/', ftype=1, vocab_only=0)
n_parts = 1

Processing part 1 of 1

Traceback (most recent call last):
  File "/mnt/c/Users/Shreyas-ITB/Downloads/llama.cpp/convert-pth-to-ggml.py", line 274, in <module>
    main()
  File "/mnt/c/Users/Shreyas-ITB/Downloads/llama.cpp/convert-pth-to-ggml.py", line 267, in main
    model = torch.load(fname_model, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
OSError: [Errno 14] Bad address`

**Command used**:  `python3 convert-pth-to-ggml.py models/7B/ 1`

Can someone help me please?

**Comment by prusnak** [comment]
The scripts have been rewritten from scratch. Try the new convert.py script from master.
