### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by edisonzf2020** [ggerganov/llama.cpp#6733]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.
python ./convert-hf-to-gguf.py /Volumes/FanData/models/dbrx-instruct --outfile /Volumes/FanData/models/GGUF/dbrx-instruct-f16.gguf --outtype f16

```
Traceback (most recent call last):
  File "/Users/fanmac/AI/llama.cpp/./convert-hf-to-gguf.py", line 2728, in <module>
    main()
  File "/Users/fanmac/AI/llama.cpp/./convert-hf-to-gguf.py", line 2722, in main
    model_instance.write()
  File "/Users/fanmac/AI/llama.cpp/./convert-hf-to-gguf.py", line 176, in write
    self.write_tensors()
  File "/Users/fanmac/AI/llama.cpp/./convert-hf-to-gguf.py", line 1554, in write_tensors
    for name, data_torch in self.get_tensors():
  File "/Users/fanmac/AI/llama.cpp/./convert-hf-to-gguf.py", line 82, in get_tensors
    ctx = cast(ContextManager[Any], safe_open(self.dir_model / part_name, framework="pt", device="cpu"))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

python ./convert.py /Volumes/FanData/models/dbrx-instruct --outfile /Volumes/FanData/models/GGUF/dbrx-instruct-f16.gguf --outtype f16

```
Traceback (most recent call last):
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 1548, in <module>
    main()
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 1480, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 1371, in load_some_model
    model_plus = merge_multifile_models(models_plus)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 804, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 783, in merge_sharded
    return {name: convert(name) for name in names}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 783, in <dictcomp>
    return {name: convert(name) for name in names}
                  ^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 758, in convert
    lazy_tensors = [model[name] for model in models]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fanmac/AI/llama.cpp/./convert.py", line 758, in <listcomp>
    lazy_tensors = [model[name] for model in models]
                    ~~~~~^^^^^^
KeyError: 'transformer.blocks.0.ffn.experts.mlp.w1'
```

**Comment by ijkeleher-anz** [comment]
Also had this issue.

Following steps (from a bunch of different Google searches showing somewhat similar issues) fixed it:

1. I had forgotten to install `git-lfs`
```shell
brew install git-lfs
```
2. I had to init lfs after installing
```shell
git install lfs
```
4. had to delete my model and then redownload, still had to use `git lfs clone` instead of `git clone`
```shell
rm -rf Meta-Llama-3-8B-Instruct
git lfs clone https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct      
```
5. then i had a weird issue that was causing the DL to hang: `warning: Multiple 'url.*..insteadof' keys with the same alias: "https://github.com/"` so had to go into my `.gitconfig` and delete multiple git url `insteadOf` redirects.

6. finally i was able to run the convert script
```shell
python llama.cpp/convert-hf-to-gguf.py Meta-Llama-3-8B-Instruct/
```
