### ISSUE TITLE
How to convert old ALPACA q4_0 model into ggjt format?

### ISSUE THREAD

**Issue by multimediaconverter** [ggerganov/llama.cpp#701]
I'm trying to use a python script, but it returns the following errors:

d:\ALPACA2>python migrate-ggml-2023-03-30-pr613.py ggml-alpaca-7b-q4.bin ggml-alpaca-7b-q4-ggjt.bin
Traceback (most recent call last):
  File "d:\ALPACA2\migrate-ggml-2023-03-30-pr613.py", line 313, in <module>
    main()
  File "d:\ALPACA2\migrate-ggml-2023-03-30-pr613.py", line 274, in main
    tokens = read_tokens(fin, hparams)
  File "d:\ALPACA2\migrate-ggml-2023-03-30-pr613.py", line 135, in read_tokens
    word = fin.read(length)
ValueError: read length must be non-negative or -1

**Comment by thefcraft** [comment]
Same error for gpt4all model

**Comment by akx** [comment]
Convert it with `convert-unversioned-ggml-to-ggml.py` first.

**Comment by multimediaconverter** [comment]
I converted alpaca model into this new format successfully.

1) convert-unversioned-ggml-to-ggml.py with tokenizer.model file and migrate-ggml-2023-03-30-pr613.py.

2) VS2017 Express x64 with AVX2 to compile examples/main.cpp on Windows. 

And what can I say: finally, it works! llama.cpp generates text ~1.5-2 times faster than alpaca.cpp
