### ISSUE TITLE
How to quantize fine-tuned llama3-8b the right way  ?

### ISSUE THREAD

**Issue by bibidentuhanoi** [ggerganov/llama.cpp#7129]
I have tried to quantize my fine-tuned llama 3 by doing these steps:

`./llama.cpp/convert.py ./Finetuned-Llama-3-70B-Instruct/ --outtype f32 --vocab-type bpe`
then :
`./llama.cpp/quantize Finetuned-Llama-3-70B-Instruct-f32.gguf Finetuned-Llama-3-70B-Instruct-q4_K_S.gguf q4_K_S 16`

when I ran it I got this: 

```
llm_load_vocab:                                             
llm_load_vocab: ************************************        
llm_load_vocab: GENERATION QUALITY WILL BE DEGRADED!        
llm_load_vocab: CONSIDER REGENERATING THE MODEL             
llm_load_vocab: ************************************        
llm_load_vocab:                     
```                        
How do I properly quantize my model ? 
Thank all

**Comment by Galunid** [comment]
`python convert-hf-to-gguf.py <path> --outtype f32` then quantize normally. For huggingface models in general use `convert-hf-to-gguf.py`

**Comment by bibidentuhanoi** [comment]
Hi, thank you for responding,  how do i  convert  my Llama 3 with BpeVocab ?
```

WARNING:hf-to-gguf:**************************************************************************************
WARNING:hf-to-gguf:** WARNING: The BPE pre-tokenizer was not recognized!
WARNING:hf-to-gguf:**          There are 2 possible reasons for this:
WARNING:hf-to-gguf:**          - the model has not been added to convert-hf-to-gguf-update.py yet
WARNING:hf-to-gguf:**          - the pre-tokenization config has changed upstream
WARNING:hf-to-gguf:**          Check your model files and convert-hf-to-gguf-update.py and update them accordingly.
WARNING:hf-to-gguf:** ref:     https://github.com/ggerganov/llama.cpp/pull/6920
WARNING:hf-to-gguf:**
WARNING:hf-to-gguf:** chkhsh:  c136ed14d01c2745d4f60a9596ae66800e2b61fa45643e72436041855ad4089d
WARNING:hf-to-gguf:**************************************************************************************
WARNING:hf-to-gguf:

Traceback (most recent call last):
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 1385, in set_vocab
    self. _set_vocab_sentencepiece()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 415, in _set_vocab_sentencepiece
    raise FileNotFoundError(f"File not found: {tokenizer_path}")
FileNotFoundError: File not found: BMO-8B-Instruct-Llama3/tokenizer.model

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 1388, in set_vocab
    self._set_vocab_llama_hf()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 471, in _set_vocab_llama_hf
    vocab = LlamaHfVocab(self.dir_model)
  File "/content/llama.cpp/convert.py", line 536, in __init__
    raise TypeError('Llama 3 must be converted with BpeVocab')
TypeError: Llama 3 must be converted with BpeVocab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 2982, in <module>
    main()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 2969, in main
    model_instance.set_vocab()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 1391, in set_vocab
    self._set_vocab_gpt2()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 342, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 244, in get_vocab_base
    tokpre = self.get_vocab_base_pre(tokenizer)
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 334, in get_vocab_base_pre
    raise NotImplementedError("BPE pre-tokenizer was not recognized - update get_vocab_base_pre()")
NotImplementedError: BPE pre-tokenizer was not recognized - update get_vocab_base_pre()
```

**Comment by ggerganov** [comment]
I think you are using an outdated tokenizer config. It's best to update to the latest LLaMA 3 tokenizer from here: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/tree/main

**Comment by bibidentuhanoi** [comment]
I moved the tokenizer configuration and related files to replace my model configuration. The script passed the BPE pre-tokenizer error, but I encountered another issue: 

```
INFO:hf-to-gguf:gguf: loading model part 'model-00001-of-00004.safetensors'
Traceback (most recent call last):
  File "//llama.cpp/convert-hf-to-gguf.py", line 2988, in <module>
    main()
  File "//llama.cpp/convert-hf-to-gguf.py", line 2982, in main
    model_instance.write()
  File "//llama.cpp/convert-hf-to-gguf.py", line 179, in write
    self.write_tensors()
  File "//llama.cpp/convert-hf-to-gguf.py", line 1430, in write_tensors
    for name, data_torch in self.get_tensors():
  File "//llama.cpp/convert-hf-to-gguf.py", line 86, in get_tensors
    ctx = cast(ContextManager[Any], safe_open(self.dir_model / part_name, framework="pt", device="cpu"))
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by teleprint-me** [comment]
@bibidentuhanoi Use `convert.py`, the vocab factory is not available in the HF script. @ggerganov This is why I want to refactor the conversion scripts.

**Comment by ggerganov** [comment]
If `convert-hf-to-gguf.py` does not work, there is no point in using `convert.py` because it does not support pre-tokenization configs needed by BPE models like LLaMA v3

@bibidentuhanoi I don't know what this error means - is it possible that the model files `*.safetensors` are not downloaded correctly?

**Comment by bibidentuhanoi** [comment]
@ggerganov , you are right, the problem lies in the model files. After quantized it, i encountered another error:
```
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA RTX A4000, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.30 MiB
llama_model_load: error loading model: check_tensor_dims: tensor 'token_embd.weight' has wrong shape; expected  4096, 128256, got  4096, 128258,     1,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'FineTuned-8B-Instruct-Llama3/finefuned-8b-instruct-llama3.Q5_K_M.gguf'
main: error: unable to load model 
```
do you have any ideas why this problem occurred ?

**Comment by bubbabug** [comment]
I'm not sure how to go about fixing this, never seen it before. I get it on every model I try to quant and now my friend is also getting this error on a model I made with mergekit... Any help would be appreciated.

```C:\Users\jacob\llama.cpp>python convert-hf-to-gguf.py Puppy_Purpose_0.69 --outtype f32
INFO:hf-to-gguf:Loading model: Puppy_Purpose_0.69
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:gguf: context length = 8192
INFO:hf-to-gguf:gguf: embedding length = 4096
INFO:hf-to-gguf:gguf: feed forward length = 14336
INFO:hf-to-gguf:gguf: head count = 32
INFO:hf-to-gguf:gguf: key-value head count = 8
INFO:hf-to-gguf:gguf: rope theta = 500000.0
INFO:hf-to-gguf:gguf: rms norm epsilon = 1e-05
INFO:hf-to-gguf:gguf: file type = 0
INFO:hf-to-gguf:Set model tokenizer
Traceback (most recent call last):
  File "C:\Users\jacob\llama.cpp\convert-hf-to-gguf.py", line 2511, in <module>
    main()
  File "C:\Users\jacob\llama.cpp\convert-hf-to-gguf.py", line 2498, in main
    model_instance.set_vocab()
  File "C:\Users\jacob\llama.cpp\convert-hf-to-gguf.py", line 1200, in set_vocab
    self. _set_vocab_sentencepiece()
  File "C:\Users\jacob\llama.cpp\convert-hf-to-gguf.py", line 507, in _set_vocab_sentencepiece
    tokenizer.LoadFromFile(str(tokenizer_path))
  File "C:\Users\jacob\miniconda3\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: D:\a\sentencepiece\sentencepiece\src\sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())]```

**Comment by Spacellary** [comment]
Yeah... Pretty stuck here with this.
