### ISSUE TITLE
Bug: convert-hf-to-gguf-update.py breaks in Windows Python 3.11.5

### ISSUE THREAD

**Issue by jim-plus** [ggerganov/llama.cpp#7706]
### What happened?

Instead of normal completion, the convert-hf-to-gguf-update.py script ran afoul of smaug-bpe with what appears to be a code page issue and halted.

### Name and Version

Current pull on branch master as of a few minutes ago.

### Relevant log output

```shell
INFO:convert-hf-to-gguf-update:chkhsh: 27949a2493fc4a9f53f5b9b029c82689cfbe5d3a1929bb25e043089e28466de6
INFO:convert-hf-to-gguf-update:normalizer: null
INFO:convert-hf-to-gguf-update:pre_tokenizer: {
    "type": "ByteLevel",
    "add_prefix_space": false,
    "trim_offsets": true,
    "use_regex": true
}
INFO:convert-hf-to-gguf-update:
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:convert-hf-to-gguf-update:model: smaug-bpe
INFO:convert-hf-to-gguf-update:tokt: 2
INFO:convert-hf-to-gguf-update:repo: https://huggingface.co/abacusai/Smaug-Llama-3-70B-Instruct
INFO:convert-hf-to-gguf-update:chktok: [198, 4815, 15073, 66597, 8004, 1602, 2355, 79772, 11187, 9468, 248, 222, 320, 8416, 8, 27623, 114, 102470, 9468, 234, 104, 31643, 320, 36773, 100166, 98634, 8, 26602, 227, 11410, 99, 247, 9468, 99, 247, 220, 18, 220, 1644, 220, 8765, 220, 8765, 18, 220, 8765, 1644, 220, 8765, 8765, 220, 8765, 8765, 18, 220, 8765, 8765, 1644, 220, 18, 13, 18, 220, 18, 497, 18, 220, 18, 1131, 18, 220, 21549, 222, 98629, 241, 45358, 233, 21549, 237, 45358, 224, 21549, 244, 21549, 115, 21549, 253, 45358, 223, 21549, 253, 21549, 95, 98629, 227, 76460, 223, 949, 37046, 101067, 19000, 23182, 102301, 9263, 18136, 16, 36827, 21909, 56560, 54337, 19175, 102118, 13373, 64571, 34694, 3114, 112203, 80112, 3436, 106451, 14196, 14196, 74694, 3089, 3089, 29249, 17523, 3001, 27708, 7801, 358, 3077, 1027, 364, 83, 820, 568, 596, 1070, 11, 364, 793, 499, 2771, 30, 364, 44, 539, 2771, 358, 3358, 1304, 433, 11, 364, 35, 499, 1093, 1063, 15600, 30, 1226, 6, 43712, 264, 64966, 43]
INFO:convert-hf-to-gguf-update:chkhsh: c136ed14d01c2745d4f60a9596ae66800e2b61fa45643e72436041855ad4089d
INFO:convert-hf-to-gguf-update:normalizer: null
INFO:convert-hf-to-gguf-update:pre_tokenizer: {
    "type": "Sequence",
    "pretokenizers": [
        {
            "type": "Split",
            "pattern": {
                "Regex": "(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"
            },
            "behavior": "Isolated",
            "invert": false
        },
        {
            "type": "ByteLevel",
            "add_prefix_space": false,
            "trim_offsets": true,
            "use_regex": false
        }
    ]
}
INFO:convert-hf-to-gguf-update:ignore_merges: false
INFO:convert-hf-to-gguf-update:
Traceback (most recent call last):
  File "C:\cygwin64\home\Jim\chat\llama.cpp\convert-hf-to-gguf-update.py", line 214, in <module>
    convert_py = convert_py_pth.read_text()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\users\jim\appdata\local\programs\python\python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\users\jim\appdata\local\programs\python\python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 17752: character maps to <undefined>
```

**Comment by Galunid** [comment]
Does it persist if you change `convert_py = convert_py_pth.read_text()` to `convert_py = convert_py_pth.read_text(encoding="utf-8")`? In your case it should be on line 214.

**Comment by Galunid** [comment]
You can also try changing the first line `# -*- coding: utf-8 -*-`.
Both should fix the issue.

**Comment by jim-plus** [comment]
I get a different error after making the change to line 214, so that's progress:
```
INFO:convert-hf-to-gguf-update:ignore_merges: false
INFO:convert-hf-to-gguf-update:
Traceback (most recent call last):
  File "C:\cygwin64\home\Jim\chat\llama.cpp\convert-hf-to-gguf-update.py", line 222, in <module>
    convert_py_pth.write_text(convert_py)
  File "C:\users\jim\appdata\local\programs\python\python311\Lib\pathlib.py", line 1079, in write_text
    return f.write(data)
           ^^^^^^^^^^^^^
  File "C:\users\jim\appdata\local\programs\python\python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 18131: character maps to <undefined>
```

**Comment by Galunid** [comment]
That makes sense. Please try the second method I provided (put  `# -*- coding: utf-8 -*-`) in the first line of the file.
The file should look like:

```python
 # -*- coding: utf-8 -*-
<whatever there was earlier>
```

**Comment by jim-plus** [comment]
Updated to python 3.11.9 on the off chance that a bugfix would help. It's the final bugfix version for 3.11. Unfortunately, no change in behavior.

**Comment by Galunid** [comment]
Sorry I wasn't precise. I meant putting that line in `convert-hf-to-gguf-update.py` (please remove it from the other file before trying this). Sorry I make you do this, but I don't have access to windows machine.

**Comment by jim-plus** [comment]
It's no trouble for me to test on Windows.

Reverted all changes and placed the comment with the coding hint in the second line of the py file (rather than the first, so Unix systems shouldn't be affected?), and then reapplied the line 214 change, and applied it to line 222 as well for the corresponding write. Unsure if the hint is necessary after the two changes.

The script appears to complete, and has updated the convert-ht-to-gguf-py script. (The broken executions before results in a zero-length script, so this is much better.) I will test and report back.

**Comment by jim-plus** [comment]
The fixes work. I may have a different issue to track down now, but we can close this one.

**Comment by jim-plus** [comment]
Just FYI, I went back and was able to get a successful run with the two explicit encoding declarations, no hint required.
