### ISSUE TITLE
Failed to create gguf for Viking 13b although support for viking pre-tokenizer was added in one of the recent llama.cpp's releases

### ISSUE THREAD

**Issue by JohnClaw** [ggerganov/llama.cpp#8225]
### What happened?

Thanks for adding support for Viking pre-tokenizer. Successfully created gguf for Viking 7b, but can't do the same thing for Viking 13b (https://huggingface.co/LumiOpen/Viking-13B). In both cases i used gguf-my-repo HF space which runs converting/quantatizing tools from the latest llama.cpp code. When i tried to create gguf for Viking 13b, i got these errors:

`Error: Error converting to fp16: b'INFO:hf-to-gguf:Loading model: Viking-13B\nINFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only\nINFO:hf-to-gguf:Set model parameters\nINFO:hf-to-gguf:gguf: context length = 4096\nINFO:hf-to-gguf:gguf: embedding length = 5120\nINFO:hf-to-gguf:gguf: feed forward length = 13824\nINFO:hf-to-gguf:gguf: head count = 40\nINFO:hf-to-gguf:gguf: key-value head count = 40\nINFO:hf-to-gguf:gguf: rope theta = 10000.0\nINFO:hf-to-gguf:gguf: rms norm epsilon = 1e-05\nINFO:hf-to-gguf:gguf: file type = 1\nINFO:hf-to-gguf:Set model tokenizer\nThe cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling transformers.utils.move_cache().\n\n\r0it [00:00, ?it/s]\x1b[A\r0it [00:00, ?it/s]\nTraceback (most recent call last):\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 1307, in set_vocab\n self. _set_vocab_sentencepiece()\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 589, in _set_vocab_sentencepiece\n raise FileNotFoundError(f"File not found: {tokenizer_path}")\nFileNotFoundError: File not found: Viking-13B/tokenizer.model\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 1310, in set_vocab\n self._set_vocab_llama_hf()\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 651, in _set_vocab_llama_hf\n vocab = gguf.LlamaHfVocab(self.dir_model)\n File "/home/user/app/llama.cpp/gguf-py/gguf/vocab.py", line 368, in init\n raise FileNotFoundError('Cannot find Llama BPE tokenizer')\nFileNotFoundError: Cannot find Llama BPE tokenizer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 3139, in \n main()\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 3124, in main\n model_instance.set_vocab()\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 1313, in set_vocab\n self._set_vocab_gpt2()\n File "/home/user/app/llama.cpp/convert-hf-to-gguf.py", line 522, in _set_vocab_gpt2\n special_vocab = gguf.SpecialVocab(self.dir_model, load_merges=True)\n File "/home/user/app/llama.cpp/gguf-py/gguf/vocab.py", line 40, in init\n self._load(Path(path))\n File "/home/user/app/llama.cpp/gguf-py/gguf/vocab.py", line 77, in _load\n self._try_load_from_config_json(path)\n File "/home/user/app/llama.cpp/gguf-py/gguf/vocab.py", line 169, in _try_load_from_config_json\n self._set_special_token(typ, config.get(f'{typ}_token_id'))\n File "/home/user/app/llama.cpp/gguf-py/gguf/vocab.py", line 110, in _set_special_token\n raise ValueError(f'invalid value for special token type {typ}: {tid}')\nValueError: invalid value for special token type pad: -1\n'`

### Name and Version

It seems that gguf-my-repo runs converting script from the newest llama.cpp build (b3266).

**Comment by JohnClaw** [comment]
Developers of Viking updated config.json and now all is ok.
