### ISSUE TITLE
Bug: Flan t5 xl conversion error (medium severity, has workaround)

### ISSUE THREAD

**Issue by steampunque** [ggerganov/llama.cpp#9028]
### What happened?

the flan_t5_xl model from google will not convert, but has a workaround as described.

### Name and Version

b3578

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
INFO:hf-to-gguf:dec.output_norm.weight,             torch.float32 --> F32, shape = {2048}
INFO:hf-to-gguf:output.weight,                      torch.float32 --> F16, shape = {2048, 32128}
Traceback (most recent call last):
  File "/usr/local/src/ai/llamacpp/llama.cpp/convert_hf_to_gguf.py", line 3953, in <module>
    main()
  File "/usr/local/src/ai/llamacpp/llama.cpp/convert_hf_to_gguf.py", line 3947, in main
    model_instance.write()
  File "/usr/local/src/ai/llamacpp/llama.cpp/convert_hf_to_gguf.py", line 387, in write
    self.prepare_tensors()
  File "/usr/local/src/ai/llamacpp/llama.cpp/convert_hf_to_gguf.py", line 262, in prepare_tensors
    for name, data_torch in self.get_tensors():
  File "/usr/local/src/ai/llamacpp/llama.cpp/convert_hf_to_gguf.py", line 173, in get_tensors
    raise ValueError(f"Mismatch between weight map and model parts for tensor names: {sym_diff}")
ValueError: Mismatch between weight map and model parts for tensor names: {'encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'}



To patch this I hand edited the model.safetensors.index.json file to remove both of these lines:

        "decoder.block.9.layer.2.layer_norm.weight": "model-00001-of-00002.safetensors",
-->     "decoder.embed_tokens.weight": "model-00001-of-00002.safetensors",
        "decoder.final_layer_norm.weight": "model-00002-of-00002.safetensors",
        "encoder.block.0.layer.0.SelfAttention.k.weight": "model-00001-of-00002.safetensors",




-->        "encoder.embed_tokens.weight": "model-00001-of-00002.safetensors",
        "encoder.final_layer_norm.weight": "model-00001-of-00002.safetensors",
        "lm_head.weight": "model-00002-of-00002.safetensors",
        "shared.weight": "model-00001-of-00002.safetensors"


The convert file comments says only one of encoder, decoder, or shared is used so I left the shared.weight in the file.

FYI this model is quite strong.  I have it running with my patched server and it scored 0.8 on LAMBADA with only 3B parameters.

bash-5.1$ lm Answer the following yes/no question by reasoning step-by-step.  Could a dandelion suffer from hepatitis?
 Hepatitis is a disease that affects the liver. Dandelions are plants. Therefore, the final answer is no.
```

**Comment by MoonRide303** [comment]
Problem is still there as of b4738 - trying to conver original [flan-t5-xl](https://huggingface.co/google/flan-t5-xl) weights from google results in

```
Traceback (most recent call last):
  File "D:\repos-git\llama.cpp\convert_hf_to_gguf.py", line 5112, in <module>
    main()
  File "D:\repos-git\llama.cpp\convert_hf_to_gguf.py", line 5106, in main
    model_instance.write()
  File "D:\repos-git\llama.cpp\convert_hf_to_gguf.py", line 439, in write
    self.prepare_tensors()
  File "D:\repos-git\llama.cpp\convert_hf_to_gguf.py", line 280, in prepare_tensors
    for name, data_torch in chain(self.generate_extra_tensors(), self.get_tensors()):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos-git\llama.cpp\convert_hf_to_gguf.py", line 183, in get_tensors
    raise ValueError(f"Missing or incomplete model files: {missing_files}")
ValueError: Missing or incomplete model files: ['model-00001-of-00002.safetensors']
```

Workaround from @steampunque helped.

**Comment by steampunque** [comment]
> Workaround from [@steampunque](https://github.com/steampunque) helped for the conversion and quantization, but I wasn't able to make this model respond sensibly with llama-server (I tried multiple templates).

The upstream llama.cpp server does not support encoder-decoder models, so if you want to run flan-t5 or madlad400 you will have to add the necessary support code to the server yourself.  What you need to do is prompt process into an encoder batch, run an encode on the encoder batch, take the output token of the encoder to seed the first decoder token, then run normal decode-only processing from thenon.  Be aware that the encoder is non causal and must contain the entire prompt, which limits prompt length to a fairly short 512 tokens for flan-t5 /madlad400  and 2048 tokens for ul2.  I have patched an experimental downstream server and I can confirm the ggml API calls for encode-decode do work, but my patch is massively incompatible with upstream due to a large number of other functionality mods I have made to the code.
