### ISSUE TITLE
Reflection-70B quantize error: Llama 3 must be converted with BpeVocab

### ISSUE THREAD

**Issue by leszekhanusz** [ggerganov/llama.cpp#9335]
### What happened?

I'm trying to quantize the [Reflection-Llama-3.1-70B](https://huggingface.co/mattshumer/Reflection-Llama-3.1-70B/tree/main) hf model.

Using the command `python convert_hf_to_gguf.py ~/hf_repos/Reflection-70B/`

And I receive the `Llama 3 must be converted with BpeVocab` TypeError.

### Name and Version

On commit `8ebe8ddebd68526757c631cd019de009697c63c2` from date `Fri Sep 6 08:56:17 2024 +0200`

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 1491, in set_vocab
    self._set_vocab_sentencepiece()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 714, in _set_vocab_sentencepiece
    tokens, scores, toktypes = self._create_vocab_sentencepiece()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 731, in _create_vocab_sentencepiece
    raise FileNotFoundError(f"File not found: {tokenizer_path}")
FileNotFoundError: File not found: /home/leszek/hf_repos/Reflection-70B/tokenizer.model

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 1494, in set_vocab
    self._set_vocab_llama_hf()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 806, in _set_vocab_llama_hf
    vocab = gguf.LlamaHfVocab(self.dir_model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leszek/git_repos/llama.cpp/gguf-py/gguf/vocab.py", line 362, in __init__
    raise TypeError('Llama 3 must be converted with BpeVocab')
TypeError: Llama 3 must be converted with BpeVocab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 4168, in <module>
    main()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 4162, in main
    model_instance.write()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 413, in write
    self.prepare_metadata(vocab_only=False)
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 406, in prepare_metadata
    self.set_vocab()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 1497, in set_vocab
    self._set_vocab_gpt2()
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 650, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/leszek/git_repos/llama.cpp/convert_hf_to_gguf.py", line 492, in get_vocab_base
    assert max(tokenizer.vocab.values()) < vocab_size
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by apepkuss** [comment]
Same issue on [mattshumer/Reflection-Llama-3.1-70B](https://huggingface.co/mattshumer/Reflection-Llama-3.1-70B)

**Comment by leszekhanusz** [comment]
Apparently there was an issue with the model and they have uploaded a new version.

After downloading the new version, the conversion is now working correctly.
