### ISSUE TITLE
Bug: Unable to quantise Uncensored Mistral NeMo Model

### ISSUE THREAD

**Issue by JamesClarke7283** [ggerganov/llama.cpp#9363]
### What happened?

I expected to be able to quantize the model.

### Name and Version
Name: convert_hf_to_gguf.py
Version : a5b5d9a1014248f385939e6739e9db9de7147e55

### What operating system are you seeing the problem on?

GNU/Linux

### Relevant information

https://huggingface.co/natong19/Mistral-Nemo-Instruct-2407-abliterated/discussions/1

**Comment by ScarletEmerald** [comment]
I was able to convert this model to gguf without issue.  I don't think I did anything special.  Unfortunately I'm not sure why it wouldn't work for you.

Example output
```
> python3 /llama.cpp/convert_hf_to_gguf.py --outtype f16 --outfile ./mistral-nemo-abliterated-fp16.gguf /Mistral-Nemo-Instruct-2407-abliterated
INFO:hf-to-gguf:Loading model: Mistral-Nemo-Instruct-2407-abliterated
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:gguf: loading model weight map from 'model.safetensors.index.json'
INFO:hf-to-gguf:gguf: loading model part 'model-00001-of-00005.safetensors'
INFO:hf-to-gguf:token_embd.weight,           torch.bfloat16 --> F16, shape = {5120, 131072}
```
etc...

**Comment by JamesClarke7283** [comment]
```
WARNING:hf-to-gguf:

WARNING:hf-to-gguf:**************************************************************************************
WARNING:hf-to-gguf:** WARNING: The BPE pre-tokenizer was not recognized!
WARNING:hf-to-gguf:**          There are 2 possible reasons for this:
WARNING:hf-to-gguf:**          - the model has not been added to convert_hf_to_gguf_update.py yet
WARNING:hf-to-gguf:**          - the pre-tokenization config has changed upstream
WARNING:hf-to-gguf:**          Check your model files and convert_hf_to_gguf_update.py and update them accordingly.
WARNING:hf-to-gguf:** ref:     https://github.com/ggerganov/llama.cpp/pull/6920
WARNING:hf-to-gguf:**
WARNING:hf-to-gguf:** chkhsh:  63b97e4253352e6f357cc59ea5b583e3a680eaeaf2632188c2b952de2588485e
WARNING:hf-to-gguf:**************************************************************************************
WARNING:hf-to-gguf:

Traceback (most recent call last):
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 1478, in set_vocab
    self._set_vocab_sentencepiece()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 701, in _set_vocab_sentencepiece
    tokens, scores, toktypes = self._create_vocab_sentencepiece()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 718, in _create_vocab_sentencepiece
    raise FileNotFoundError(f"File not found: {tokenizer_path}")
FileNotFoundError: File not found: Mistral/Mistral-Nemo-Instruct-2407-abliterated/tokenizer.model

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 1481, in set_vocab
    self._set_vocab_llama_hf()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 793, in _set_vocab_llama_hf
    vocab = gguf.LlamaHfVocab(self.dir_model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/ollama/llama.cpp/gguf-py/gguf/vocab.py", line 362, in __init__
    raise TypeError('Llama 3 must be converted with BpeVocab')
TypeError: Llama 3 must be converted with BpeVocab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 4157, in <module>
    main()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 4151, in main
    model_instance.write()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 415, in write
    self.prepare_metadata(vocab_only=False)
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 408, in prepare_metadata
    self.set_vocab()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 1484, in set_vocab
    self._set_vocab_gpt2()
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 637, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 496, in get_vocab_base
    tokpre = self.get_vocab_base_pre(tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/ollama/./llama.cpp/convert_hf_to_gguf.py", line 628, in get_vocab_base_pre
    raise NotImplementedError("BPE pre-tokenizer was not recognized - update get_vocab_base_pre()")
NotImplementedError: BPE pre-tokenizer was not recognized - update get_vocab_base_pre()
```
I tried with latest and got the error.

**Comment by JamesClarke7283** [comment]
Actually without running the convert update script it works now, thanks.
