### ISSUE TITLE
The problem with the conversion with the new convert.py

### ISSUE THREAD

**Issue by SrVill** [ggerganov/llama.cpp#966]
Hello! Help me figure out:

F:\Models\digitous-Alpacino13b>convert.py --dump-single F:\Models\digitous-Alpacino13b\4bit.safetensors
Traceback (most recent call last):
  File "F:\Models\digitous-Alpacino13b\convert.py", line 1145, in <module>
    main()
  File "F:\Models\digitous-Alpacino13b\convert.py", line 1116, in main
    model_plus = lazy_load_file(args.model)
  File "F:\Models\digitous-Alpacino13b\convert.py", line 853, in lazy_load_file
    return lazy_load_safetensors_file(fp, path)
  File "F:\Models\digitous-Alpacino13b\convert.py", line 753, in lazy_load_safetensors_file
    model = {name: convert(info) for (name, info) in header.items()}
  File "F:\Models\digitous-Alpacino13b\convert.py", line 753, in <dictcomp>
    model = {name: convert(info) for (name, info) in header.items()}
  File "F:\Models\digitous-Alpacino13b\convert.py", line 745, in convert
    assert 0 <= begin <= end <= len(byte_buf)
AssertionError

What is the error here - in the script or maybe there is a problem in the model? The model is from here: https://huggingface.co/digitous/Alpacino13b/tree/main

**Comment by kickturn** [comment]
Same error here

**Comment by kickturn** [comment]
Apparently I fixed it by using Linux? Use WSL and run it.

**Comment by comex** [comment]
Let's see...

**Comment by kickturn** [comment]
yup just checked and the commit fixed it.

**Comment by SrVill** [comment]
The same mistake. Maybe I'm doing something wrong?

C:\llama.cpp>convert.py 4bit.safetensors --outtype q4_1 --outfile 4ggml.bin
Loading model file 4bit.safetensors
Traceback (most recent call last):
  File "C:\llama.cpp\convert.py", line 1145, in <module>
    main()
  File "C:\llama.cpp\convert.py", line 1125, in main
    model_plus = load_some_model(args.model)
  File "C:\llama.cpp\convert.py", line 1052, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "C:\llama.cpp\convert.py", line 853, in lazy_load_file
    return lazy_load_safetensors_file(fp, path)
  File "C:\llama.cpp\convert.py", line 753, in lazy_load_safetensors_file
    model = {name: convert(info) for (name, info) in header.items()}
  File "C:\llama.cpp\convert.py", line 753, in <dictcomp>
    model = {name: convert(info) for (name, info) in header.items()}
  File "C:\llama.cpp\convert.py", line 745, in convert
    assert 0 <= begin <= end <= len(byte_buf)
AssertionError

**Comment by NextGA-OSS** [comment]
Seeing similar issues still. Latest repo trying to set up an apple m2 implementation using mixtral:
```
% python3 convert.py ./models/mixtral-instruct-8x7b/ \
         --outfile ./models/mixtral-instruct-8x7b/ggml-model-f16.gguf \
         --outtype f16
Loading model file models/mixtral-instruct-8x7b/model-00001-of-00019.safetensors
Traceback (most recent call last):
  File "/Users/micahelbyrns/Documents/Workspace/llama/convert.py", line 1279, in <module>
    main()
  File "/Users/micahelbyrns/Documents/Workspace/llama/convert.py", line 1207, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/micahelbyrns/Documents/Workspace/llama/convert.py", line 1140, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/micahelbyrns/Documents/Workspace/llama/convert.py", line 797, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: models/mixtral-instruct-8x7b/model-00001-of-00019.safetensors
```

**Comment by prusnak** [comment]
> Seeing similar issues still.

It's a very different issue. Open a new issue.

**Comment by shrijayan** [comment]
> SrVill

Facing the same issue in Google Colab. Any Solution?
