### ISSUE TITLE
Bug: KeyError: 'num_attention_heads'

### ISSUE THREAD

**Issue by DK013** [ggerganov/llama.cpp#9754]
### What happened?

While trying to convert [allenai/MolmoE-1B-0924](https://huggingface.co/allenai/MolmoE-1B-0924/tree/main) model using convert_hf_to_gguf.py both in my macOS and also using the [ggml-org/gguf-my-repo](https://huggingface.co/spaces/ggml-org/gguf-my-repo) I run into this error:

**Local Machine:**
```
Traceback (most recent call last):
  File "/Users/zer0/Desktop/gguf_gui/llama.cpp/convert_hf_to_gguf.py", line 4430, in <module>
    main()
  File "/Users/zer0/Desktop/gguf_gui/llama.cpp/convert_hf_to_gguf.py", line 4424, in main
    model_instance.write()
  File "/Users/zer0/Desktop/gguf_gui/llama.cpp/convert_hf_to_gguf.py", line 433, in write
    self.prepare_tensors()
  File "/Users/zer0/Desktop/gguf_gui/llama.cpp/convert_hf_to_gguf.py", line 297, in prepare_tensors
    for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zer0/Desktop/gguf_gui/llama.cpp/convert_hf_to_gguf.py", line 3025, in modify_tensors
    n_head = self.hparams["num_attention_heads"]
             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'num_attention_heads'
```

**GGUF my repo:**
```
Error: Error converting to fp16: b'INFO:hf-to-gguf:Loading model: MolmoE-1B-0924
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:gguf: loading model part 'pytorch_model.bin'
Traceback (most recent call last):
 File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 4430, in 
  main()
   File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 4424, in main
    model_instance.write()
     File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 433, in write
 self.prepare_tensors()
 File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 297, in prepare_tensors
 for new_name, data_torch in (self.modify_tensors(data_torch, name, bid)):
 File "/home/user/app/llama.cpp/convert_hf_to_gguf.py", line 3025, in modify_tensors
 n_head = self.hparams["num_attention_heads"]
KeyError: 'num_attention_heads'
```

I so far I have no clue what causes this. any heads up on the cause or how to fix it would be super helpful. Thanks

### Name and Version

commit [8c475b9](https://github.com/ggerganov/llama.cpp/commit/8c475b97b8ba7d678d4c9904b1161bd8811a9b44)

### What operating system are you seeing the problem on?

Mac, Other? (Please let us know in description)

**Comment by Threelies** [comment]
Try to check your [self.hparams] ,look for it in configs and match the key, or add manually .

**Comment by DK013** [comment]
Ok, so, your comment is very non-descriptive @Threelies, but thanks for pointing me to the right direction. I appreciate that. it seems the `num_attention_heads` key is missing from the model config. I'll add it as see if anything else is missing or not.

**Comment by DK013** [comment]
After further evaluating it seems that this model doesn't share the same architecture as llama or other supported architectures. so it will always fail.
